In [ ]:
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
import pandas as pd
import os
import config 
# Database credentials — replace with your actual values
DB_USER 
DB_PASSWORD 
DB_HOST 
DB_PORT 
DB_NAME 
TABLE_NAME
CSV_FILE_PATH 
FIELDS_TERMINATED_BY = ","  # Change if needed
LINES_TERMINATED_BY = "\n"  # Change if needed
IGNORE_HEADER_LINES = 1     # Skip he

In [2]:

try:
    # Step 1: Connect to MySQL server (no database yet)
    engine = create_engine(
        f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}",
        echo=False  # Set to False to disable SQL logging
    )

    # Step 2: Create database if it doesn't exist
    with engine.connect() as conn:
        conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {DB_NAME}"))
        print(f"Database '{DB_NAME}' created or already exists.")

    # Step 3: Connect to the newly created database
    db_engine = create_engine(
        f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
        echo=False
    )

    # Step 4: Test connection
    with db_engine.connect() as conn:
        result = conn.execute(text("SELECT DATABASE()"))
        print(f"Connected to database: {result.scalar()}")

except SQLAlchemyError as e:
    print("Error connecting to MySQL:", e)
except Exception as e:
    print("Unexpected error:", e)

Database 'olympics' created or already exists.
Connected to database: olympics

In [10]:
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String,Numeric

# Create engine for MySQL
engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
    echo=False
)

# Create metadata object
meta = MetaData()

# Define table
olympics_data = Table(
    "olympics_data", meta,
    Column("id", Integer),
    Column("name", String(100)),
    Column("sex", String(10)),
    Column("age", Integer),
    Column("height", Numeric(5, 2)),
    Column("weight", Numeric(5, 2)),
    Column("noc", String(10)),
    Column("year", Integer),
    Column("sport", String(50)),
    Column("event", String(100)),
    Column("medal", String(50)),
    Column("country", String(50))
)

# Create the table in the database
meta.create_all(engine)

print("Table 'olympics_data' created successfully.")
engine = create_engine('sqlite:///users.db', echo=True)

2026-10-14 13:25:55,142 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2026-10-14 13:25:55,143 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-10-14 13:25:55,146 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2026-10-14 13:25:55,147 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-10-14 13:25:55,150 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2026-10-14 13:25:55,151 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-10-14 13:25:55,154 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-10-14 13:25:55,155 INFO sqlalchemy.engine.Engine DESCRIBE `olympics`.`olympics_data`
2026-10-14 13:25:55,156 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-10-14 13:25:55,160 INFO sqlalchemy.engine.Engine
CREATE TABLE olympics_data (
	id INTEGER,
	name VARCHAR(100),
	sex VARCHAR(10),
	age INTEGER,
	height NUMERIC(5, 2),
	weight NUMERIC(5, 2),
	noc VARCHAR(10),
	year INTEGER,
	sport VARCHAR(50),
	event VARCHAR(100),
	medal VARCHAR(50),
	country VARCHAR(50)
)


2026-10-14 13:25:55,161 INFO sqlalchemy.engine.Engine [no key 0.00114s] {}
2026-10-14 13:25:55,203 INFO sqlalchemy.engine.Engine COMMIT
Table 'olympics_data' created successfully.

In [5]:
url = r"C:\Users\dwigh\Downloads\olympics_cleaned_v4.csv"
df = pd.read_csv(url,sep=",")

In [6]:
df.head(5)

,ID,Name,Sex,Age,Height,Weight,NOC,Year,Sport,Event,Medal,country
0,1,A Dijiang,M,24.0,180.0,80.0,CHN,1992,Basketball,Basketball Men's Basketball,NaN,China
1,2,A Lamusi,M,23.0,170.0,60.0,CHN,2012,Judo,Judo Men's Extra-Lightweight,NaN,China
2,602,Abudoureheman,M,22.0,182.0,75.0,CHN,2000,Boxing,Boxing Men's Middleweight,NaN,China
3,1463,Ai Linuer,M,25.0,160.0,62.0,CHN,2004,Wrestling,"Wrestling Men's Lightweight, Greco-Roman",NaN,China
4,1464,Ai Yanhan,F,14.0,168.0,54.0,CHN,2016,Swimming,Swimming Women's 200 metres Freestyle,NaN,China

In [7]:
import numpy as np
df['Medal'] = df['Medal'].replace('', np.nan).fillna('')
df.head(5)

,ID,Name,Sex,Age,Height,Weight,NOC,Year,Sport,Event,Medal,country
0,1,A Dijiang,M,24.0,180.0,80.0,CHN,1992,Basketball,Basketball Men's Basketball,,China
1,2,A Lamusi,M,23.0,170.0,60.0,CHN,2012,Judo,Judo Men's Extra-Lightweight,,China
2,602,Abudoureheman,M,22.0,182.0,75.0,CHN,2000,Boxing,Boxing Men's Middleweight,,China
3,1463,Ai Linuer,M,25.0,160.0,62.0,CHN,2004,Wrestling,"Wrestling Men's Lightweight, Greco-Roman",,China
4,1464,Ai Yanhan,F,14.0,168.0,54.0,CHN,2016,Swimming,Swimming Women's 200 metres Freestyle,,China

In [12]:

engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}", 
    echo = False
)


try:
    # Bulk insert into table 'olympics_data'
    df.to_sql(
    name="olympics_data",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=5000,  # Larger batch size
    method="multi"
    )
    print("Bulk insert completed successfully.")
except SQLAlchemyError as e:
    print(f"Error during bulk insert: {e}")

Bulk insert completed successfully.

In [13]:
%load_ext sql

In [14]:

connection_url = f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

%sql {connection_url}

In [ ]:
# to work sqlmagic
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [48]:
%%sql

select * 
from olympics_data
limit 5;

 * mysql+pymysql://root:***@localhost:3306/olympics

[(1, 'A Dijiang', 'M', 24, Decimal('180.00'), Decimal('80.00'), 'CHN', 1992, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (2, 'A Lamusi', 'M', 23, Decimal('170.00'), Decimal('60.00'), 'CHN', 2012, 'Judo', "Judo Men's Extra-Lightweight", '', 'China'),
 (602, 'Abudoureheman', 'M', 22, Decimal('182.00'), Decimal('75.00'), 'CHN', 2000, 'Boxing', "Boxing Men's Middleweight", '', 'China'),
 (1463, 'Ai Linuer', 'M', 25, Decimal('160.00'), Decimal('62.00'), 'CHN', 2004, 'Wrestling', "Wrestling Men's Lightweight, Greco-Roman", '', 'China'),
 (1464, 'Ai Yanhan', 'F', 14, Decimal('168.00'), Decimal('54.00'), 'CHN', 2016, 'Swimming', "Swimming Women's 200 metres Freestyle", '', 'China')]

#### Problem 1 
Display the names of athletes who won a gold medal in the 2008 Olympics and whose height is greater than the average height of all athletes in the 2008 Olympics.

In [63]:
%%sql

SELECT * 
FROM olympics_data
WHERE Year=2008 
    AND Medal = 'Gold'
    AND Height > 
    (SELECT AVG(Height) FROM 
     olympics_data WHERE Year=2008)

 * mysql+pymysql://root:***@localhost:3306/olympics

[(54900, 'Jin Ziwei', 'F', 22, Decimal('183.00'), Decimal('75.00'), 'CHN', 2008, 'Rowing', "Rowing Women's Quadruple Sculls", 'Gold', 'China'),
 (69968, 'Lin Dan', 'M', 24, Decimal('177.00'), Decimal('70.00'), 'CHN', 2008, 'Badminton', "Badminton Men's Singles", 'Gold', 'China'),
 (70710, 'Liu Zige', 'F', 19, Decimal('181.00'), Decimal('70.00'), 'CHN', 2008, 'Swimming', "Swimming Women's 200 metres Butterfly", 'Gold', 'China'),
 (78706, 'Meng Guanliang', 'M', 31, Decimal('185.00'), Decimal('90.00'), 'CHN', 2008, 'Canoeing', "Canoeing Men's Canadian Doubles, 500 metres", 'Gold', 'China'),
 (91043, 'Pang Wei', 'M', 22, Decimal('178.00'), Decimal('77.00'), 'CHN', 2008, 'Shooting', "Shooting Men's Air Pistol, 10 metres", 'Gold', 'China'),
 (118408, 'Tang Bin', 'F', 22, Decimal('182.00'), Decimal('72.00'), 'CHN', 2008, 'Rowing', "Rowing Women's Quadruple Sculls", 'Gold', 'China'),
 (121038, 'Tong Wen', 'F', 25, Decimal('180.00'), Decimal('130.00'), 'CHN', 2008, 'Judo', "Judo Women's Heavyweight", 'Gold', 'China'),
 (128481, 'Wang Jiao', 'F', 20, Decimal('177.00'), Decimal('72.00'), 'CHN', 2008, 'Wrestling', "Wrestling Women's Heavyweight, Freestyle", 'Gold', 'China'),
 (128520, 'Wang Liqin', 'M', 30, Decimal('192.00'), Decimal('85.00'), 'CHN', 2008, 'Table Tennis', "Table Tennis Men's Team", 'Gold', 'China'),
 (131992, 'Xi Aihua', 'F', 26, Decimal('182.00'), Decimal('80.00'), 'CHN', 2008, 'Rowing', "Rowing Women's Quadruple Sculls", 'Gold', 'China'),
 (132549, 'Yang Wenjun', 'M', 24, Decimal('178.00'), Decimal('78.00'), 'CHN', 2008, 'Canoeing', "Canoeing Men's Canadian Doubles, 500 metres", 'Gold', 'China'),
 (134572, 'Zhang Xiaoping', 'M', 26, Decimal('188.00'), Decimal('81.00'), 'CHN', 2008, 'Boxing', "Boxing Men's Light-Heavyweight", 'Gold', 'China'),
 (134592, 'Zhang Yangyang', 'F', 19, Decimal('185.00'), Decimal('80.00'), 'CHN', 2008, 'Rowing', "Rowing Women's Quadruple Sculls", 'Gold', 'China'),
 (134781, 'Zhong Man', 'M', 25, Decimal('190.00'), Decimal('75.00'), 'CHN', 2008, 'Fencing', "Fencing Men's Sabre, Individual", 'Gold', 'China'),
 (3761, 'Mads Christian Kruse Andersen', 'M', 30, Decimal('187.00'), Decimal('75.00'), 'DEN', 2008, 'Rowing', "Rowing Men's Lightweight Coxless Fours", 'Gold', 'Denmark'),
 (31224, 'Eskild Balschmidt Ebbesen', 'M', 36, Decimal('185.00'), Decimal('75.00'), 'DEN', 2008, 'Rowing', "Rowing Men's Lightweight Coxless Fours", 'Gold', 'Denmark'),
 (31259, 'Thomas Ebert', 'M', 35, Decimal('184.00'), Decimal('72.00'), 'DEN', 2008, 'Rowing', "Rowing Men's Lightweight Coxless Fours", 'Gold', 'Denmark'),
 (56133, 'Morten Jrgensen', 'M', 23, Decimal('183.00'), Decimal('73.00'), 'DEN', 2008, 'Rowing', "Rowing Men's Lightweight Coxless Fours", 'Gold', 'Denmark'),
 (60730, 'Martin Kirketerp Ibsen', 'M', 26, Decimal('188.00'), Decimal('80.00'), 'DEN', 2008, 'Sailing', 'Sailing Mixed Skiff', 'Gold', 'Denmark'),
 (128801, 'Jonas Warrer', 'M', 29, Decimal('181.00'), Decimal('77.00'), 'DEN', 2008, 'Sailing', 'Sailing Mixed Skiff', 'Gold', 'Denmark'),
 (17156, 'Frederike Jacobie "Mieke" Cabout', 'F', 22, Decimal('182.00'), Decimal('70.00'), 'NED', 2008, 'Water Polo', "Water Polo Women's Water Polo", 'Gold', 'Netherlands'),
 (27081, 'Inge Dekker', 'F', 22, Decimal('183.00'), Decimal('67.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (47117, 'Frederike Johanna Maria "Femke" Heemskerk', 'F', 20, Decimal('180.00'), Decimal('68.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (61132, 'Noeki Klein', 'F', 25, Decimal('179.00'), Decimal('80.00'), 'NED', 2008, 'Water Polo', "Water Polo Women's Water Polo", 'Gold', 'Netherlands'),
 (64249, 'Ranomi Kromowidjojo', 'F', 17, Decimal('180.00'), Decimal('72.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (82988, 'Eefke Marije Mulder', 'F', 30, Decimal('177.00'), Decimal('63.00'), 'NED', 2008, 'Hockey', "Hockey Women's Hockey", 'Gold', 'Netherlands'),
 (107518, 'Hinkelien Schreuder', 'F', 24, Decimal('179.00'), Decimal('61.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (112169, 'Miloushka Yasemin Smit', 'F', 23, Decimal('178.00'), Decimal('70.00'), 'NED', 2008, 'Water Polo', "Water Polo Women's Water Polo", 'Gold', 'Netherlands'),
 (124153, 'Naomi Frances van As', 'F', 25, Decimal('179.00'), Decimal('63.00'), 'NED', 2008, 'Hockey', "Hockey Women's Hockey", 'Gold', 'Netherlands'),
 (124185, 'Iefke van Belkum', 'F', 22, Decimal('185.00'), Decimal('75.00'), 'NED', 2008, 'Water Polo', "Water Polo Women's Water Polo", 'Gold', 'Netherlands'),
 (124422, 'Ilse Suzanne van der Meijden', 'F', 19, Decimal('185.00'), Decimal('71.00'), 'NED', 2008, 'Water Polo', "Water Polo Women's Water Polo", 'Gold', 'Netherlands'),
 (124495, 'Maarten van der Weijden', 'M', 27, Decimal('205.00'), Decimal('92.00'), 'NED', 2008, 'Swimming', "Swimming Men's 10 kilometres Open Water", 'Gold', 'Netherlands'),
 (124874, 'Manon van Rooijen', 'F', 26, Decimal('178.00'), Decimal('67.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (125745, 'Magdalena Johanna Maria "Marleen" Veldhuis', 'F', 29, Decimal('182.00'), Decimal('67.00'), 'NED', 2008, 'Swimming', "Swimming Women's 4 x 100 metres Freestyle Relay", 'Gold', 'Netherlands'),
 (36595, 'Marit Malm Frafjord', 'F', 22, Decimal('182.00'), Decimal('78.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (42984, 'Kari Aalvik Grimsb', 'F', 23, Decimal('180.00'), Decimal('80.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (45343, 'Gro Hammerseng (-Hammerseng-Edin)', 'F', 28, Decimal('180.00'), Decimal('68.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (45928, 'Katrine Lunde Haraldsen', 'F', 28, Decimal('181.00'), None, 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (66847, 'Tonje Larsen', 'F', 33, Decimal('184.00'), Decimal('72.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (72292, 'Kristine Lunde-Borgersen', 'F', 28, Decimal('181.00'), Decimal('67.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (87263, 'Tonje Nstvold', 'F', 23, Decimal('178.00'), None, 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (87485, 'Katja Johanna Alice Nyberg', 'F', 28, Decimal('182.00'), Decimal('76.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (112580, 'Gril Snorroeggen', 'F', 23, Decimal('177.00'), None, 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (113612, 'Else-Marthe Srlie Lybekk', 'F', 29, Decimal('177.00'), Decimal('76.00'), 'NOR', 2008, 'Handball', "Handball Women's Handball", 'Gold', 'Norway'),
 (120054, 'Andreas Thorkildsen', 'M', 26, Decimal('188.00'), Decimal('90.00'), 'NOR', 2008, 'Athletics', "Athletics Men's Javelin Throw", 'Gold', 'Norway'),
 (122530, 'Olaf Karl Tufte', 'M', 32, Decimal('193.00'), Decimal('94.00'), 'NOR', 2008, 'Rowing', "Rowing Men's Single Sculls", 'Gold', 'Norway'),
 (25098, 'Georgeta Damian-Andrunache', 'F', 32, Decimal('178.00'), Decimal('75.00'), 'ROU', 2008, 'Rowing', "Rowing Women's Coxless Pairs", 'Gold', 'Romania'),
 (116663, 'Viorica Susanu', 'F', 32, Decimal('186.00'), Decimal('77.00'), 'ROU', 2008, 'Rowing', "Rowing Women's Coxless Pairs", 'Gold', 'Romania'),
 (57280, 'Gerd Kanter', 'M', 29, Decimal('196.00'), Decimal('125.00'), 'EST', 2008, 'Athletics', "Athletics Men's Discus Throw", 'Gold', 'Estonia'),
 (73, 'Luc Abalo', 'M', 23, Decimal('182.00'), Decimal('86.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (93, 'Jol Marc Abati', 'M', 38, Decimal('190.00'), Decimal('85.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (583, 'Julien Absalon', 'M', 27, Decimal('180.00'), Decimal('68.00'), 'FRA', 2008, 'Cycling', "Cycling Men's Mountainbike, Cross-Country", 'Gold', 'France'),
 (10674, 'Alain Andr Louis Edmond Bernard', 'M', 25, Decimal('196.00'), Decimal('90.00'), 'FRA', 2008, 'Swimming', "Swimming Men's 100 metres Freestyle", 'Gold', 'France'),
 (16492, 'Cdric Burdet', 'M', 33, Decimal('195.00'), Decimal('98.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (28639, 'Didier Dominique Dinart', 'M', 31, Decimal('197.00'), Decimal('104.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (34829, 'Jrme Fernandez', 'M', 31, Decimal('199.00'), Decimal('106.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (40339, 'Bertrand Fabien Gille', 'M', 30, Decimal('187.00'), Decimal('98.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (40342, 'Guillaume Alain Gille', 'M', 32, Decimal('192.00'), Decimal('97.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (40547, 'Olivier Damien Girault', 'M', 35, Decimal('183.00'), Decimal('86.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (43698, 'Michal Yves Robert Guigou', 'M', 26, Decimal('179.00'), Decimal('79.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (54120, 'Fabrice Jeannet', 'M', 27, Decimal('193.00'), Decimal('85.00'), 'FRA', 2008, 'Fencing', "Fencing Men's epee, Team", 'Gold', 'France'),
 (54122, 'Jrme Jeannet', 'M', 31, Decimal('190.00'), Decimal('85.00'), 'FRA', 2008, 'Fencing', "Fencing Men's epee, Team", 'Gold', 'France'),
 (57389, 'Nikola Karabatic', 'M', 24, Decimal('194.00'), Decimal('104.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (57393, 'Daouda Karabou', 'M', 32, Decimal('198.00'), Decimal('92.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (58646, 'Christophe Maurice Jean Kemp', 'M', 33, Decimal('193.00'), Decimal('105.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (71441, 'Nicolas Pierre Lopez', 'M', 27, Decimal('180.00'), Decimal('60.00'), 'FRA', 2008, 'Fencing', "Fencing Men's Sabre, Team", 'Gold', 'France'),
 (84527, 'Daniel Narcisse', 'M', 28, Decimal('189.00'), Decimal('93.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (89072, 'Thierry Omeyer', 'M', 31, Decimal('192.00'), Decimal('93.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (92139, 'Cdric Paty', 'M', 27, Decimal('194.00'), Decimal('93.00'), 'FRA', 2008, 'Handball', "Handball Men's Handball", 'Gold', 'France'),
 (94887, 'Julien Pillet', 'M', 30, Decimal('184.00'), Decimal('75.00'), 'FRA', 2008, 'Fencing', "Fencing Men's Sabre, Team", 'Gold', 'France'),
 (101252, 'Ulrich Dimitri Robeiri', 'M', 25, Decimal('190.00'), Decimal('80.00'), 'FRA', 2008, 'Fencing', "Fencing Men's epee, Team", 'Gold', 'France'),
 (105520, 'Boris Louis Sanson', 'M', 27, Decimal('193.00'), Decimal('80.00'), 'FRA', 2008, 'Fencing', "Fencing Men's Sabre, Team", 'Gold', 'France'),
 (23703, 'Sal Craviotto Rivero', 'M', 23, Decimal('192.00'), Decimal('98.00'), 'ESP', 2008, 'Canoeing', "Canoeing Men's Kayak Doubles, 500 metres", 'Gold', 'Spain'),
 (31296, 'Fernando Echavarri Erasum', 'M', 35, Decimal('180.00'), Decimal('76.00'), 'ESP', 2008, 'Sailing', 'Sailing Mixed Multihull', 'Gold', 'Spain'),
 (70806, 'Joan Llaneras Rossell', 'M', 39, Decimal('180.00'), Decimal('65.00'), 'ESP', 2008, 'Cycling', "Cycling Men's Points Race", 'Gold', 'Spain'),
 (84006, 'Rafael Nadal Parera', 'M', 22, Decimal('185.00'), Decimal('80.00'), 'ESP', 2008, 'Tennis', "Tennis Men's Singles", 'Gold', 'Spain'),
 (93286, 'Carlos Prez Rial', 'M', 29, Decimal('182.00'), Decimal('84.00'), 'ESP', 2008, 'Canoeing', "Canoeing Men's Kayak Doubles, 500 metres", 'Gold', 'Spain'),
 (105246, 'Samuel Snchez Gonzlez', 'M', 30, Decimal('181.00'), Decimal('68.00'), 'ESP', 2008, 'Cycling', "Cycling Men's Road Race, Individual", 'Gold', 'Spain'),
 (104185, 'Hadi Saei Bonehkohal', 'M', 32, Decimal('182.00'), Decimal('79.00'), 'IRI', 2008, 'Taekwondo', "Taekwondo Men's Welterweight", 'Gold', 'Iran'),
 (31103, 'Rumyana Dimitrova Dzhadzharova-Neykova', 'F', 35, Decimal('177.00'), Decimal('77.00'), 'BUL', 2008, 'Rowing', "Rowing Women's Single Sculls", 'Gold', 'Bulgaria'),
 (17656, 'Roberto Cammarelle', 'M', 28, Decimal('190.00'), Decimal('101.50'), 'ITA', 2008, 'Boxing', "Boxing Men's Super-Heavyweight", 'Gold', 'Italy'),
 (80165, 'Andrea Minguzzi', 'M', 26, Decimal('179.00'), Decimal('84.00'), 'ITA', 2008, 'Wrestling', "Wrestling Men's Light-Heavyweight, Greco-Roman", 'Gold', 'Italy'),
 (92854, 'Federica Pellegrini', 'F', 20, Decimal('177.00'), Decimal('65.00'), 'ITA', 2008, 'Swimming', "Swimming Women's 200 metres Freestyle", 'Gold', 'Italy'),
 (107891, 'Alex Schwazer', 'M', 23, Decimal('185.00'), Decimal('73.00'), 'ITA', 2008, 'Athletics', "Athletics Men's 50 kilometres Walk", 'Gold', 'Italy'),
 (117787, 'Matteo Tagliariol', 'M', 25, Decimal('188.00'), Decimal('78.00'), 'ITA', 2008, 'Fencing', "Fencing Men's epee, Individual", 'Gold', 'Italy'),
 (13404, 'Valeriy Viktorovich Borchin', 'M', 21, Decimal('178.00'), Decimal('63.00'), 'RUS', 2008, 'Athletics', "Athletics Men's 20 kilometres Walk", 'Gold', 'Russia'),
 (14365, 'Svetlana Anatolyevna Boyko', 'F', 36, Decimal('180.00'), Decimal('63.00'), 'RUS', 2008, 'Fencing', "Fencing Women's Foil, Team", 'Gold', 'Russia'),
 (19580, 'Rakhim Ruslanovich Chakhkiyev', 'M', 25, Decimal('183.00'), Decimal('91.00'), 'RUS', 2008, 'Boxing', "Boxing Men's Heavyweight", 'Gold', 'Russia'),
 (27457, 'Yelena Vyacheslavovna Dementyeva (-Afinogenova)', 'F', 26, Decimal('180.00'), Decimal('64.00'), 'RUS', 2008, 'Tennis', "Tennis Women's Singles", 'Gold', 'Russia'),
 (52471, 'Nataliya Sergeyevna Ishchenko', 'F', 22, Decimal('177.00'), Decimal('60.00'), 'RUS', 2008, 'Synchronized Swimming', "Synchronized Swimming Women's Team", 'Gold', 'Russia'),
 (59505, 'Aslanbek Vitalyevich Khushtov', 'M', 28, Decimal('180.00'), Decimal('96.00'), 'RUS', 2008, 'Wrestling', "Wrestling Men's Heavyweight, Greco-Roman", 'Gold', 'Russia'),
 (81027, 'Andrey Sergeyevich Moiseyev', 'M', 29, Decimal('195.00'), Decimal('83.00'), 'RUS', 2008, 'Modern Pentathlon', "Modern Pentathlon Men's Individual", 'Gold', 'Russia'),
 (83407, 'Sharvani Gadzhikurbanovich Muradov', 'M', 23, Decimal('182.00'), Decimal('96.00'), 'RUS', 2008, 'Wrestling', "Wrestling Men's Heavyweight, Freestyle", 'Gold', 'Russia'),
 (89254, 'Maksim Aleksandrovich Opalev', 'M', 29, Decimal('184.00'), Decimal('93.00'), 'RUS', 2008, 'Canoeing', "Canoeing Men's Canadian Singles, 500 metres", 'Gold', 'Russia'),
 (104992, 'Gulnara Iskanderovna Samitova-Galkina', 'F', 30, Decimal('178.00'), Decimal('54.00'), 'RUS', 2008, 'Athletics', "Athletics Women's 3,000 metres Steeplechase", 'Gold', 'Russia'),
 (106394, 'Buvaysar Khamidovich Saytiyev', 'M', 33, Decimal('180.00'), Decimal('74.00'), 'RUS', 2008, 'Wrestling', "Wrestling Men's Middleweight, Freestyle", 'Gold', 'Russia'),
 (110475, 'Andrey Aleksandrovich Silnov', 'M', 23, Decimal('198.00'), Decimal('83.00'), 'RUS', 2008, 'Athletics', "Athletics Men's High Jump", 'Gold', 'Russia'),
 (34363, 'Federico Julin Fazio', 'M', 21, Decimal('195.00'), Decimal('85.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (38456, 'Ezequiel Marcelo Garay Gonzlez', 'M', 21, Decimal('182.00'), Decimal('87.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (91382, 'Nicols Martn Pareja', 'M', 24, Decimal('177.00'), Decimal('70.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (93409, 'Walter Fernando Prez', 'M', 33, Decimal('178.00'), Decimal('78.00'), 'ARG', 2008, 'Cycling', "Cycling Men's Madison", 'Gold', 'Argentina'),
 (100993, 'Juan Romn Riquelme', 'M', 30, Decimal('182.00'), Decimal('75.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (102339, 'Sergio Germn Romero', 'M', 21, Decimal('191.00'), Decimal('86.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (113302, 'Jos Ernesto Sosa', 'M', 23, Decimal('179.00'), Decimal('73.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (123595, 'scar Alfredo Ustari', 'M', 22, Decimal('183.00'), Decimal('84.00'), 'ARG', 2008, 'Football', "Football Men's Football", 'Gold', 'Argentina'),
 (71437, 'Mijan Lpez Nez', 'M', 25, Decimal('198.00'), Decimal('130.00'), 'CUB', 2008, 'Wrestling', "Wrestling Men's Super-Heavyweight, Greco-Roman", 'Gold', 'Cuba'),
 (101483, 'Dayron Robles Planes', 'M', 21, Decimal('191.00'), Decimal('80.00'), 'CUB', 2008, 'Athletics', "Athletics Men's 110 metres Hurdles", 'Gold', 'Cuba'),
 (72, 'Aleksey Aleksandrovich Abalmasov', 'M', 28, Decimal('180.00'), Decimal('83.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Kayak Fours, 1,000 metres", 'Gold', 'Belarus'),
 (12741, 'Aleksandr Viktorovich Bogdanovich', 'M', 26, Decimal('191.00'), Decimal('97.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Canadian Doubles, 1,000 metres", 'Gold', 'Belarus'),
 (12742, 'Andrey Viktorovich Bogdanovich', 'M', 20, Decimal('193.00'), Decimal('87.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Canadian Doubles, 1,000 metres", 'Gold', 'Belarus'),
 (70535, 'Artur Sergeyevich Litvinchuk', 'M', 20, Decimal('189.00'), Decimal('83.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Kayak Fours, 1,000 metres", 'Gold', 'Belarus'),
 (73862, 'Vadim Gennadyevich Makhnyov', 'M', 28, Decimal('196.00'), Decimal('100.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Kayak Fours, 1,000 metres", 'Gold', 'Belarus'),
 (78744, 'Oksana Vladimirovna Menkova', 'F', 26, Decimal('186.00'), Decimal('85.00'), 'BLR', 2008, 'Athletics', "Athletics Women's Hammer Throw", 'Gold', 'Belarus'),
 (94189, 'Roman Ivanovich Petrushenko', 'M', 27, Decimal('191.00'), Decimal('91.00'), 'BLR', 2008, 'Canoeing', "Canoeing Men's Kayak Fours, 1,000 metres", 'Gold', 'Belarus'),
 (1017, 'Nathan Ghar-Jun Adrian', 'M', 19, Decimal('198.00'), Decimal('100.00'), 'USA', 2008, 'Swimming', "Swimming Men's 4 x 100 metres Freestyle Relay", 'Gold', 'USA'),
 (4505, 'Carmelo Kyan Anthony', 'M', 24, Decimal('203.00'), Decimal('109.00'), 'USA', 2008, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (5971, 'Seimone Delicia Augustus', 'F', 24, Decimal('183.00'), Decimal('74.00'), 'USA', 2008, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (7283, 'Lloy James Ball', 'M', 36, Decimal('203.00'), Decimal('95.00'), 'USA', 2008, 'Volleyball', "Volleyball Men's Volleyball", 'Gold', 'USA'),
 (10337, 'Richard "Ricky" Berens', 'M', 20, Decimal('188.00'), Decimal('93.00'), 'USA', 2008, 'Swimming', "Swimming Men's 4 x 200 metres Freestyle Relay", 'Gold', 'USA'),
 (13372, 'Carlos Austin Boozer, Jr.', 'M', 26, Decimal('206.00'), Decimal('117.00'), 'USA', 2008, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (13739, 'Christopher Wesson "Chris" Bosh', 'M', 24, Decimal('208.00'), Decimal('104.00'), 'USA', 2008, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (15606, 'Stephanie Karenmonica Brown-Trafton', 'F', 28, Decimal('193.00'), Decimal('100.00'), 'USA', 2008, 'Athletics', "Athletics Women's Discus Throw", 'Gold', 'USA'),
 (15891, 'Kobe Bean Bryant', 'M', 29, Decimal('198.00'), Decimal('100.00'), 'USA', 2008, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (19044, 'Tamika Devonne Catchings', 'F', 29, Decimal('185.00'), Decimal('77.00'), 'USA', 2008, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (21947, 'Bryan Ezra Tsumoru Clay', 'M', 28, Decimal('180.00'), Decimal('83.00'), 'USA', 2008, 'Athletics', "Athletics Men's Decathlon", 'Gold', 'USA'),
 (21990, 'Kerron Stephon Clement', 'M', 22, Decimal('188.00'), Decimal('86.00'), 'USA', 2008, 'Athletics', "Athletics Men's 4 x 400 metres Relay", 'Gold', 'USA'),

#### Problem 2
Display the names of athletes who won a medal in the sport of basketball in the 2016 Olympics and whose weight is less than the average weight of all athletes who won a medal in the 2016 Olympics.

In [62]:
%%sql

SELECT * FROM 
olympics_data
    WHERE Year=2016 AND Sport='Basketball'
    AND Medal IS NOT NULL
    AND Weight > 
(SELECT AVG(Weight) 
FROM olympics_data
    WHERE Year=2016
    AND Medal IS NOT NULL)

 * mysql+pymysql://root:***@localhost:3306/olympics

[(20245, 'Chen Nan', 'F', 33, Decimal('195.00'), Decimal('94.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (28664, 'Ding Yanyuhang', 'M', 22, Decimal('200.00'), Decimal('91.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (38422, 'Gao Song', 'F', 24, Decimal('190.00'), Decimal('85.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (43951, 'Guo Ailun', 'M', 22, Decimal('192.00'), Decimal('85.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (50611, 'Huang Hongpin', 'F', 27, Decimal('195.00'), Decimal('98.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (50646, 'Huang Sijing', 'F', 20, Decimal('190.00'), Decimal('82.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (69349, 'Li Gen', 'M', 27, Decimal('196.00'), Decimal('110.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (69452, 'Li Muhao', 'M', 24, Decimal('218.00'), Decimal('115.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (71920, 'Lu Wen', 'F', 26, Decimal('188.00'), Decimal('78.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (109244, 'Shao Ting', 'F', 26, Decimal('184.00'), Decimal('75.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (116263, 'Sui Ran', 'M', 24, Decimal('193.00'), Decimal('96.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (116481, 'Sun Mengran', 'F', 24, Decimal('195.00'), Decimal('83.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (116482, 'Sun Mengxin', 'F', 23, Decimal('190.00'), Decimal('84.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (128644, 'Wang Zhelin', 'M', 22, Decimal('214.00'), Decimal('100.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (131781, 'Wu Di', 'F', 22, Decimal('182.00'), Decimal('75.00'), 'CHN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'China'),
 (132953, 'Yi Jianlian', 'M', 28, Decimal('213.00'), Decimal('113.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (134410, 'Zhai Xiaochuan', 'M', 23, Decimal('204.00'), Decimal('100.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (134649, 'Zhao Jiwei', 'M', 20, Decimal('185.00'), Decimal('80.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (134806, 'Zhou Peng', 'M', 26, Decimal('206.00'), Decimal('102.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (134808, 'Zhou Qi', 'M', 20, Decimal('217.00'), Decimal('95.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (135273, 'Zou Yuchen', 'M', 20, Decimal('203.00'), Decimal('107.00'), 'CHN', 2016, 'Basketball', "Basketball Men's Basketball", '', 'China'),
 (3294, 'Marielle Amant', 'F', 26, Decimal('190.00'), Decimal('84.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (6213, 'Valriane Ayayi', 'F', 22, Decimal('184.00'), Decimal('72.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (8648, 'Nicolas Batum', 'M', 27, Decimal('203.00'), Decimal('105.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (21495, 'Hlna Ciak', 'F', 26, Decimal('197.00'), Decimal('89.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (26052, 'Nando de Colo', 'M', 29, Decimal('196.00'), Decimal('91.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (28209, 'Boris Babacar Diaw-Riffiod', 'M', 34, Decimal('203.00'), Decimal('115.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (28715, 'Antoine Diot', 'M', 27, Decimal('193.00'), Decimal('86.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (39393, 'Mickal Gelabale', 'M', 33, Decimal('201.00'), Decimal('98.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (40911, 'Rudy Gobert-Bourgarel', 'M', 24, Decimal('215.00'), Decimal('113.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (43288, 'Sandrine Gruda', 'F', 29, Decimal('193.00'), Decimal('83.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (48323, 'Thomas Heurtel', 'M', 27, Decimal('188.00'), Decimal('83.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (56671, 'Charles Lombahe-Kahudi', 'M', 30, Decimal('197.00'), Decimal('104.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (57025, 'Latitia Kamba', 'F', 29, Decimal('187.00'), Decimal('78.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (67183, 'Joffrey Lauvergne', 'M', 24, Decimal('209.00'), Decimal('115.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (80621, 'Nwal-Endn Miyem', 'F', 28, Decimal('188.00'), Decimal('87.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (91680, 'William Anthony "Tony" Parker, Jr.', 'M', 34, Decimal('186.00'), Decimal('80.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (94772, 'Florent Pitrus', 'M', 35, Decimal('202.00'), Decimal('103.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (120356, 'Kim Tillie', 'M', 28, Decimal('211.00'), Decimal('105.00'), 'FRA', 2016, 'Basketball', "Basketball Men's Basketball", '', 'France'),
 (132134, 'Isabelle Yacoubou-Dehoui', 'F', 30, Decimal('190.00'), Decimal('104.00'), 'FRA', 2016, 'Basketball', "Basketball Women's Basketball", '', 'France'),
 (576, 'Alejandro "lex" Abrines Redondo', 'M', 23, Decimal('198.00'), Decimal('93.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (17402, 'Jos Manuel Caldern Borrallo', 'M', 34, Decimal('191.00'), Decimal('90.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (21935, 'Vctor Claver Arocas', 'M', 27, Decimal('206.00'), Decimal('107.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (34876, 'Rodolfo "Rudy" Fernndez Farrs', 'M', 31, Decimal('196.00'), Decimal('84.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (38960, 'Pau Gasol Sez', 'M', 36, Decimal('215.00'), Decimal('115.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (40243, 'Laura Gil Collado', 'F', 24, Decimal('191.00'), Decimal('78.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (48109, 'Guillermo Gustavo "Willy" Hernangmez Geuer', 'M', 22, Decimal('210.00'), Decimal('115.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (70865, 'Sergio Llull Meli', 'M', 28, Decimal('192.00'), Decimal('91.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (80294, 'Nikola Miroti Stajovi', 'M', 25, Decimal('208.00'), Decimal('100.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (84776, 'Juan Carlos Navarro Feijoo', 'M', 36, Decimal('193.00'), Decimal('82.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (85808, 'Laura Nicholls Gonzlez', 'F', 27, Decimal('190.00'), Decimal('90.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (91878, 'Mara Lucila Pascua Surez', 'F', 33, Decimal('196.00'), Decimal('93.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (97884, 'Laura Quevedo Caizares', 'F', 20, Decimal('185.00'), Decimal('74.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (100219, 'Felipe Reyes Cabaas', 'M', 36, Decimal('205.00'), Decimal('109.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (101810, 'Leonor Rodrguez Manso', 'F', 24, Decimal('180.00'), Decimal('72.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (101854, 'Sergio Rodrguez Gmez', 'M', 30, Decimal('191.00'), Decimal('80.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (103209, 'Ricard "Ricky" Rubio Vives', 'M', 25, Decimal('193.00'), Decimal('82.00'), 'ESP', 2016, 'Basketball', "Basketball Men's Basketball", 'Bronze', 'Spain'),
 (121237, 'Alba Torrens Salom', 'F', 26, Decimal('195.00'), Decimal('80.00'), 'ESP', 2016, 'Basketball', "Basketball Women's Basketball", 'Silver', 'Spain'),
 (742, 'Roberto Acua', 'M', 25, Decimal('208.00'), Decimal('109.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (15852, 'Nicols Brussino', 'M', 23, Decimal('200.00'), Decimal('84.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (17677, 'Facundo Campazzo', 'M', 25, Decimal('181.00'), Decimal('85.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (26913, 'Gabriel Alejandro Deck', 'M', 21, Decimal('197.00'), Decimal('107.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (27256, 'Carlos Francisco Delfino', 'M', 33, Decimal('196.00'), Decimal('95.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (27307, 'Marcos Nicols Dela', 'M', 24, Decimal('209.00'), Decimal('105.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (38810, 'Patricio Garino Gullotta', 'M', 23, Decimal('196.00'), Decimal('96.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (40451, 'Emanuel David "Manu" Ginbili Maccari', 'M', 39, Decimal('198.00'), Decimal('91.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (66653, 'Nicols Laprovittola', 'M', 26, Decimal('193.00'), Decimal('88.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (73680, 'Leonardo Andrs "Leo" Mainoldi', 'M', 31, Decimal('204.00'), Decimal('106.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (86706, 'Andrs Marcelo Nocioni Roux', 'M', 36, Decimal('201.00'), Decimal('102.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (107958, 'Luis Alberto Scola Balvoa', 'M', 36, Decimal('206.00'), Decimal('108.00'), 'ARG', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Argentina'),
 (69115, 'Yelena Stepanovna Levchenko', 'F', 33, Decimal('195.00'), Decimal('86.00'), 'BLR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Belarus'),
 (96196, 'Mariya Vladimirovna Popova', 'F', 22, Decimal('189.00'), Decimal('84.00'), 'BLR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Belarus'),
 (112600, 'Yekaterina Andreyevna Snytina', 'F', 30, Decimal('188.00'), Decimal('78.00'), 'BLR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Belarus'),
 (122002, 'Tatyana Vladimirovna Troina', 'F', 35, Decimal('188.00'), Decimal('78.00'), 'BLR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Belarus'),
 (125987, 'Anastasiya Vladimirovna Veremeyenko', 'F', 29, Decimal('192.00'), Decimal('82.00'), 'BLR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Belarus'),
 (17266, 'Bahar alar', 'F', 27, Decimal('190.00'), Decimal('76.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (17918, 'Tue Cantez', 'F', 25, Decimal('188.00'), Decimal('85.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (60430, 'ebnem Nezahat Kimyacolu', 'F', 33, Decimal('182.00'), Decimal('80.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (105319, 'LaToya Antoinette "Lara" Sanders (Pringle-)', 'F', 29, Decimal('191.00'), Decimal('77.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (108674, 'Tilbe enyrek', 'F', 21, Decimal('189.00'), Decimal('86.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (132979, 'Nevriye Ylmaz', 'F', 36, Decimal('192.00'), Decimal('85.00'), 'TUR', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Turkey'),
 (4505, 'Carmelo Kyan Anthony', 'M', 32, Decimal('203.00'), Decimal('109.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (5971, 'Seimone Delicia Augustus', 'F', 32, Decimal('183.00'), Decimal('74.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (7956, 'Harrison Bryce Jordan Barnes', 'M', 24, Decimal('203.00'), Decimal('102.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (16923, 'Jimmy Butler III', 'M', 26, Decimal('201.00'), Decimal('99.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (19044, 'Tamika Devonne Catchings', 'F', 37, Decimal('185.00'), Decimal('77.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (19901, 'Tina Alexandria Charles', 'F', 27, Decimal('193.00'), Decimal('88.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (23497, 'DeMarcus Amir Cousins', 'M', 25, Decimal('210.00'), Decimal('122.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (27357, 'Elena Delle Donne', 'F', 26, Decimal('195.00'), Decimal('86.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (27743, 'DeMar Darnell DeRozan', 'M', 26, Decimal('201.00'), Decimal('99.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (30807, 'Kevin Wayne Durant', 'M', 27, Decimal('206.00'), Decimal('105.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (36558, 'Sylvia Shaqueria Fowles', 'F', 30, Decimal('198.00'), Decimal('90.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (39561, 'Paul George', 'M', 26, Decimal('206.00'), Decimal('99.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (42622, 'Draymond Jamal Green', 'M', 26, Decimal('200.00'), Decimal('104.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (42994, 'Brittney Yevette Griner', 'F', 25, Decimal('203.00'), Decimal('94.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (52383, 'Kyrie Andrew Irving', 'M', 24, Decimal('190.00'), Decimal('87.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (55874, 'Hyland DeAndre Jordan, Jr.', 'M', 28, Decimal('211.00'), Decimal('120.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (71822, 'Kyle Lowry', 'M', 30, Decimal('183.00'), Decimal('93.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (81671, 'Maya April Moore', 'F', 27, Decimal('183.00'), Decimal('79.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (115132, 'Breanna Mackenzie Stewart', 'F', 21, Decimal('193.00'), Decimal('79.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (119932, 'Klay Alexander Thompson', 'M', 26, Decimal('200.00'), Decimal('97.00'), 'USA', 2016, 'Basketball', "Basketball Men's Basketball", 'Gold', 'USA'),
 (129913, 'Lindsay Marie Whalen', 'F', 34, Decimal('175.00'), Decimal('72.00'), 'USA', 2016, 'Basketball', "Basketball Women's Basketball", 'Gold', 'USA'),
 (1701, 'Joshua Emmanuel "Josh" Akognon', 'M', 30, Decimal('189.00'), Decimal('83.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (3445, 'Abdul Wahab "Alade" Aminu', 'M', 28, Decimal('210.00'), Decimal('102.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (28688, 'Ikechukwu Somtochukwu "Ike" Diogu', 'M', 32, Decimal('206.00'), Decimal('115.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (32859, 'Ebi Ere', 'M', 35, Decimal('196.00'), Decimal('97.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (39248, 'Michael Patrick Gbinije', 'M', 24, Decimal('201.00'), Decimal('90.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (51526, 'Ekene Chukwu Brian Ibekwe', 'M', 31, Decimal('206.00'), Decimal('100.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (67293, 'Olaseni Abdul-Jelili "Shane" Lawal', 'M', 29, Decimal('208.00'), Decimal('102.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (88163, 'Andy Ogide', 'M', 29, Decimal('204.00'), Decimal('107.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (88201, 'Chamberlain Nnaemeka Oguchi', 'M', 30, Decimal('198.00'), Decimal('90.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (123304, 'Michael Daniel Chukwuma  Umeh', 'M', 31, Decimal('187.00'), Decimal('88.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (123679, 'Benjamin Chukwukelo "Ben" Uzoh', 'M', 28, Decimal('191.00'), Decimal('92.00'), 'NGR', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Nigeria'),
 (683, 'Natalie Chioma Achonwa', 'F', 23, Decimal('190.00'), Decimal('86.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (6245, 'Miranda Joy Ayim', 'F', 28, Decimal('190.00'), Decimal('72.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (83536, 'Lizanne Murphy', 'F', 32, Decimal('185.00'), Decimal('75.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (95507, 'Katherine Plouffe', 'F', 23, Decimal('190.00'), Decimal('89.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (95508, 'Michelle Plouffe', 'F', 23, Decimal('190.00'), Decimal('82.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (98417, 'Folade Nayo Raincock-Ekunwe', 'F', 24, Decimal('187.00'), Decimal('75.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (112447, 'Kimberly Ann "Kim" Smith-Gaucher', 'F', 32, Decimal('182.00'), Decimal('72.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (118748, 'Tamara T. Tatham', 'F', 30, Decimal('185.00'), Decimal('79.00'), 'CAN', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Canada'),
 (3711, 'David Emil Andersen', 'M', 36, Decimal('211.00'), Decimal('102.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (6949, 'Cameron David Bairstow', 'M', 25, Decimal('206.00'), Decimal('118.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (8923, 'Aron John Baynes', 'M', 29, Decimal('208.00'), Decimal('115.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (12795, 'Andrew Michael Bogut', 'M', 31, Decimal('213.00'), Decimal('122.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (15292, 'Ryan Broekhoff', 'M', 25, Decimal('201.00'), Decimal('93.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (16770, 'Natalie Burton', 'F', 27, Decimal('194.00'), Decimal('76.00'), 'AUS', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Australia'),
 (17591, 'Elizabeth Folake "Liz" Cambage', 'F', 24, Decimal('203.00'), Decimal('98.00'), 'AUS', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Australia'),
 (27355, 'Matthew "Matt" Dellavedova', 'M', 25, Decimal('193.00'), Decimal('89.00'), 'AUS', 2016, 'Basketball', "Basketball Men's Basketball", '', 'Australia'),
 (39543, 'Cayla George', 'F', 27, Decimal('192.00'), Decimal('90.00'), 'AUS', 2016, 'Basketball', "Basketball Women's Basketball", '', 'Australia'),

#### Problem 3
Display the names of all athletes who have won a medal in the sport of swimming in both the 2008 and 2016 Olympics.

In [61]:
%%sql 


SELECT Name 
FROM olympics_data
    WHERE Year=2008 OR Year=2016
    AND Sport='Swimming' 
    AND Medal IS NOT NULL

 * mysql+pymysql://root:***@localhost:3306/olympics

[('Ai Yanhan',),
 ('Ai Yanhan',),
 ('Ao Changrong',),
 ('Bai Xue',),
 ('Bao Chunlai',),
 ('Bao Yingying',),
 ('Bao Yingying',),
 ('Bi Yan',),
 ('Bian Hongmin',),
 ('Bian Lan',),
 ('Bu Tao',),
 ('Cai Li',),
 ('Cai Li',),
 ('Cai Tongtong',),
 ('Cai Yun',),
 ('Cao Lei',),
 ('Cao Yifei',),
 ('Cao Yue',),
 ('Cao Zhongrong',),
 ('Chang Chunfeng',),
 ('Chang Yongxiang',),
 ('Chen Huijia',),
 ('Chen Jianghua',),
 ('Chen Jie',),
 ('Chen Jin',),
 ('Chen Jingwen',),
 ('Chen Junyi',),
 ('Chen Kun',),
 ('Chen Ling',),
 ('Chen Ling',),
 ('Chen Nan',),
 ('Chen Qi',),
 ('Chen Qian',),
 ('Chen Qiuqi',),
 ('Chen Ruolin',),
 ('Chen Ruolin',),
 ('Chen Tao',),
 ('Chen Xiaoli',),
 ('Chen Xiexia',),
 ('Chen Xinyi',),
 ('Chen Xiuke',),
 ('Chen Yanqing',),
 ('Chen Yanyan',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yibing',),
 ('Chen Yin',),
 ('Chen Ying',),
 ('Chen Zhaoxia',),
 ('Chen Zhong',),
 ('Chen Zhongyun',),
 ('Chen Zuo',),
 ('Chen Zuo',),
 ('Cheng Fei',),
 ('Cheng Fei',),
 ('Cheng Fei',),
 ('Cheng Fei',),
 ('Cheng Fei',),
 ('Cheng Hui',),
 ('Chou Tao',),
 ('Chu Yafei',),
 ('Cui Jianjun',),
 ('Cui Lei',),
 ('Cui Liang',),
 ('Cui Peng',),
 ('Deng Daokun',),
 ('Deng Haiyang',),
 ('Deng Jian',),
 ('Deng Linlin',),
 ('Deng Linlin',),
 ('Deng Linlin',),
 ('Deng Linlin',),
 ('Deng Linlin',),
 ('Ding Fuxue',),
 ('Dong Dong',),
 ('Dong Fangzhuo',),
 ('Dong Guotao',),
 ('Dong Jie',),
 ('Dong Jimin',),
 ('Dong Xiaoqin',),
 ('Du Feng',),
 ('Du Jing',),
 ('Du Li',),
 ('Du Li',),
 ('Fang Yanqiao',),
 ('Fang Yingchao',),
 ('Fei Fengji',),
 ('Feng Fei',),
 ('Feng Kun',),
 ('Feng Liming',),
 ('Feng Xiaoting',),
 ('Feng Yong',),
 ('Feng Yong',),
 ('Fu Baorong',),
 ('Fu Haifeng',),
 ('Fu Yuanhui',),
 ('Fu Yuanhui',),
 ('Gao Ao',),
 ('Gao Lihua',),
 ('Gao Lin',),
 ('Gao Ling',),
 ('Gao Min',),
 ('Gao Min',),
 ('Gao Shuying',),
 ('Gao Yulan',),
 ('Ge Weiqing',),
 ('Gong Lijiao',),
 ('Gu Beibei',),
 ('Gu Junjie',),
 ('Gu Yasha',),
 ('Gu Yu',),
 ('Guo Dan',),
 ('Guo Dan',),
 ('Guo Jia',),
 ('Guo Jingjing',),
 ('Guo Jingjing',),
 ('Guo Kang',),
 ('Guo Lei',),
 ('Guo Peng',),
 ('Guo Shuang',),
 ('Guo Wenjun',),
 ('Guo Youhua',),
 ('Guo Yue',),
 ('Guo Yue',),
 ('Guo Zhendong',),
 ('Han Duan',),
 ('Han Ling',),
 ('Han Peng',),
 ('Han Wenxia',),
 ('Han Zhidong',),
 ('Hanati Silamu',),
 ('Hao Junmin',),
 ('Hao Kexin',),
 ('He Chong',),
 ('He Hanbin',),
 ('He Jianbin',),
 ('He Jin',),
 ('He Kexin',),
 ('He Kexin',),
 ('He Kexin',),
 ('He Wenna',),
 ('He Yanzhu',),
 ('He Yi',),
 ('Hou Fenglian',),
 ('Hou Yawen',),
 ('Hu Binyuan',),
 ('Hu Huiren',),
 ('Hu Kai',),
 ('Hu Kai',),
 ('Hu Liang',),
 ('Hu Minghai',),
 ('Hu Qing',),
 ('Hu Xianqiang',),
 ('Hu Yixuan',),
 ('Hua Tian',),
 ('Huang Dongjie',),
 ('Huang Haiqiang',),
 ('Huang Haiyang',),
 ('Huang Haiyang',),
 ('Huang Hong',),
 ('Huang Jialing',),
 ('Huang Junxia',),
 ('Huang Shanshan',),
 ('Huang Shaohua',),
 ('Huang Xu',),
 ('Huang Xu',),
 ('Huang Xu',),
 ('Huang Xu',),
 ('Huang Xu',),
 ('Huang Xuechen',),
 ('Huang Yaojiang',),
 ('Huang Zhipeng',),
 ('Huang Zhipeng',),
 ('Huang Zhongming',),
 ('Huang Zuping',),
 ('Huang Zuping',),
 ('Huo Liang',),
 ('Huo Liang',),
 ('Ji Jianhua',),
 ('Ji Wei',),
 ('Jia Delong',),
 ('Jia Yubing',),
 ('Jia Zhanbo',),
 ('Jia Zhanbo',),
 ('Jiang Fudong',),
 ('Jiang Huachen',),
 ('Jiang Lan',),
 ('Jiang Lin',),
 ('Jiang Lin',),
 ('Jiang Ning',),
 ('Jiang Tingting',),
 ('Jiang Tingting',),
 ('Jiang Wenwen',),
 ('Jiang Wenwen',),
 ('Jiang Xishang',),
 ('Jiang Yuyuan',),
 ('Jiang Yuyuan',),
 ('Jiang Yuyuan',),
 ('Jiang Yuyuan',),
 ('Jiang Yuyuan',),
 ('Jiao Huafeng',),
 ('Jiao Liuyang',),
 ('Jiao Shuai',),
 ('Jin Di',),
 ('Jin Ziwei',),
 ('Lai Zhongjian',),
 ('Lei Donghui',),
 ('Lei Sheng',),
 ('Li Bin',),
 ('Li Bing',),
 ('Li Chenhao',),
 ('Li Chunxia',),
 ('Li Fei',),
 ('Li Guangyuan',),
 ('Li Guangyuan',),
 ('Li Guojie',),
 ('Li Guojie',),
 ('Li Hexin',),
 ('Li Hongli',),
 ('Li Hongquan',),
 ('Li Hongxia',),
 ('Li Hongyang',),
 ('Li Jianbo',),
 ('Li Jiaxing',),
 ('Li Jie',),
 ('Li Jingjing',),
 ('Li Juan',),
 ('Li Jun',),
 ('Li Lei',),
 ('Li Ling',),
 ('Li Ling',),
 ('Li Meiju',),
 ('Li Mo',),
 ('Li Na',),
 ('Li Na',),
 ('Li Nan',),
 ('Li Qi',),
 ('Li Qiang',),
 ('Li Qin',),
 ('Li Runrun',),
 ('Li Shanshan',),
 ('Li Shanshan',),
 ('Li Shanshan',),
 ('Li Shanshan',),
 ('Li Shuang',),
 ('Li Wei',),
 ('Li Weifeng',),
 ('Li Weiliang',),
 ('Li Weiwei',),
 ('Li Wenhao',),
 ('Li Wenquan',),
 ('Li Wenquan',),
 ('Li Xiang',),
 ('Li Xiang',),
 ('Li Xiang',),
 ('Li Xiangyu',),
 ('Li Xiaomei',),
 ('Li Xiaoni',),
 ('Li Xiaopeng',),
 ('Li Xiaopeng',),
 ('Li Xiaopeng',),
 ('Li Xiaopeng',),
 ('Li Xiaopeng',),
 ('Li Xiaopeng',),
 ('Li Xuanxu',),
 ('Li Xuanxu',),
 ('Li Yajun',),
 ('Li Yan',),
 ('Li Yanfeng',),
 ('Li Yang',),
 ('Li Yang',),
 ('Li Yanxi',),
 ('Li Yanyan',),
 ('Li Zhen',),
 ('Li Zhenqiang',),
 ('Li Zhenqiang',),
 ('Li Zhenzhu',),
 ('Li Zhesi',),
 ('Li Zhuhao',),
 ('Li Zhuhao',),
 ('Li Zhuhao',),
 ('Li Zhuhong',),
 ('Liang Lei',),
 ('Liang Peixing',),
 ('Liang Zhongxing',),
 ('Liao Hui',),
 ('Lin Dan',),
 ('Lin Miao',),
 ('Lin Yongqing',),
 ('Lin Yue',),
 ('Lin Zhongzai',),
 ('Liu Chunhong',),
 ('Liu Dan',),
 ('Liu Deli',),
 ('Liu Feiliang',),
 ('Liu Guini',),
 ('Liu Haili',),
 ('Liu Haitao',),
 ('Liu Hong',),
 ('Liu Huana',),
 ('Liu Jing',),
 ('Liu Kai',),
 ('Liu Lina',),
 ('Liu Ou',),
 ('Liu Ping',),
 ('Liu Qing',),
 ('Liu Renwang',),
 ('Liu Sa',),
 ('Liu Wei',),
 ('Liu Xiang',),
 ('Liu Xiang',),
 ('Liu Xiantang',),
 ('Liu Xiaobo',),
 ('Liu Xiaomei',),
 ('Liu Xiaosheng',),
 ('Liu Yanan',),
 ('Liu Yaxin',),
 ('Liu Ying',),
 ('Liu Yingzi',),
 ('Liu Yun',),
 ('Liu Zhen',),
 ('Liu Zhenli',),
 ('Liu Zhongsheng',),
 ('Liu Zige',),
 ('Long Qingquan',),
 ('Lou Jiahui',),
 ('Lu Bin',),
 ('Lu Chunlong',),
 ('Lu Fenghui',),
 ('Lu Jiangang',),
 ('Lu Lan',),
 ('Lu Wei',),
 ('Lu Ying',),
 ('Lu Ying',),
 ('Lu Yong',),
 ('Lu Yuanyang',),
 ('Lu Zhiwu',),
 ('Luo Fangming',),
 ('Luo Nan',),
 ('Luo Xi',),
 ('Luo Youjia',),
 ('Ma Huanhuan',),
 ('Ma Lin',),
 ('Ma Lin',),
 ('Ma Liyun',),
 ('Ma Sanyi',),
 ('Ma Xuejun',),
 ('Ma Yibo',),
 ('Ma Yunwen',),
 ('Mao Feilian',),
 ('Meng Guanliang',),
 ('Meng Jun',),
 ('Meng Lang',),
 ('Meng Lang',),
 ('Meng Lizhi',),
 ('Meng Xuguang',),
 ('Meng Yan',),
 ('Miao Lijie',),
 ('Miao Qing',),
 ('Na Yubo',),
 ('Ni Hong',),
 ('Ning Zetao',),
 ('Ning Zetao',),
 ('Ning Zetao',),
 ('Ning Zetao',),
 ('Pan Fengzhen',),
 ('Pan Song',),
 ('Pan Xia',),
 ('Pan Yao',),
 ('Pan Yao',),
 ('Pang Jiaying',),
 ('Pang Jiaying',),
 ('Pang Jiaying',),
 ('Pang Jiaying',),
 ('Pang Jiaying',),
 ('Pang Wei',),
 ('Peng Shuai',),
 ('Peng Shuai',),
 ('Pu Wei',),
 ('Qi Haifeng',),
 ('Qi Hui',),
 ('Qi Hui',),
 ('Qian Zhenhua',),
 ('Qiao Leiying',),
 ('Qin Kai',),
 ('Qin Kai',),
 ('Qin Wangping',),
 ('Qiong Maimaitituersun',),
 ('Qiu Jian',),
 ('Qiu Jian',),
 ('Qiu Shengjiong',),
 ('Qiu Ziao',),
 ('Qiu Ziao',),
 ('Qu Jingyu',),
 ('Qu Ridong',),
 ('Qu Xiaoming',),
 ('Ren Chengyuan',),
 ('Ren Jie',),
 ('Ren Qi',),
 ('Ren Ye',),
 ('Shang Keyuan',),
 ('Shao Ning',),
 ('Shao Tingting',),
 ('Shen Duo',),
 ('Shen Duo',),
 ('Shen Duo',),
 ('Shen Duo',),
 ('Shen Duo',),
 ('Shen Jie',),
 ('Shen Jie',),
 ('Shen Longyuan',),
 ('Shen Qiong',),
 ('Shen Sheng',),
 ('Sheng Jiang',),
 ('Shi Dongpeng',),
 ('Shi Feng',),
 ('Shi Hairong',),
 ('Shi Haoran',),
 ('Shi Jinglin',),
 ('Shi Jinglin',),
 ('Shi Jinglin',),
 ('Shi Na',),
 ('Shi Zhiyong',),
 ('Shu Junrong',),
 ('Si Riguleng',),
 ('Si Rijigawa',),
 ('Si Tianfeng',),
 ('Song Aimin',),
 ('Song Dan',),
 ('Song Kai',),
 ('Song Qingling',),
 ('Song Xiaoyun',),
 ('Song Xiaqun',),
 ('Song Yi',),
 ('Su Rifeng',),
 ('Su Wanwen',),
 ('Su Wanwen',),
 ('Sui Feifei',),
 ('Sui Jianshuang',),
 ('Sui Shengsheng',),
 ('Sun Chao',),
 ('Sun Chao',),
 ('Sun Dan',),
 ('Sun Guoqiang',),
 ('Sun Huizi',),
 ('Sun Jie',),
 ('Sun Laimiao',),
 ('Sun Li',),
 ('Sun Lingfeng',),
 ('Sun Meichen',),
 ('Sun Ping',),
 ('Sun Qiuting',),
 ('Sun Tianjun',),
 ('Sun Tiantian',),
 ('Sun Wei',),
 ('Sun Xiaolei',),
 ('Sun Yang',),
 ('Sun Yang',),
 ('Sun Yang',),
 ('Sun Yang',),
 ('Sun Yang',),
 ('Sun Yang',),
 ('Sun Yating',),
 ('Sun Ye',),
 ('Sun Ye',),
 ('Sun Yue',),
 ('Sun Yujun',),
 ('Tan Feihu',),
 ('Tan He',),
 ('Tan Miao',),
 ('Tan Miao',),
 ('Tan Wangsong',),
 ('Tan Xue',),
 ('Tan Xue',),
 ('Tan Ying',),
 ('Tan Ying',),
 ('Tan Zongliang',),
 ('Tan Zongliang',),
 ('Tang Bin',),
 ('Tang Chunling',),
 ('Tang Jingzhi',),
 ('Tang Xiaoyin',),
 ('Tang Yi',),
 ('Tang Yi',),
 ('Tao Yujia',),
 ('Tao Zhinan',),
 ('Teng Fei',),
 ('Tian Jia',),
 ('Tian Jianxia',),
 ('Tian Jun',),
 ('Tian Liang',),
 ('Tong Wen',),
 ('Wan Houliang',),
 ('Wang Aichen',),
 ('Wang Beiming',),
 ('Wang Chao',),
 ('Wang Dandan',),
 ('Wang Daqing',),
 ('Wang Feng',),
 ('Wang Feng',),
 ('Wang Hao',),
 ('Wang Hao',),
 ('Wang Hao',),
 ('Wang He',),
 ('Wang Jiancheng',),
 ('Wang Jiao',),
 ('Wang Jie',),
 ('Wang Jing',),
 ('Wang Jing',),
 ('Wang Jingfeng',),
 ('Wang Jingpin',),
 ('Wang Jingzhi',),
 ('Wang Jingzhi',),
 ('Wang Juan',),
 ('Wang Lei',),
 ('Wang Lei',),
 ('Wang Lei',),
 ('Wang Liqin',),
 ('Wang Liqin',),
 ('Wang Long',),
 ('Wang Min',),
 ('Wang Na',),
 ('Wang Nan',),
 ('Wang Nan',),
 ('Wang Nan',),
 ('Wang Nan',),
 ('Wang Qiang',),
 ('Wang Shasha',),
 ('Wang Shijia',),
 ('Wang Shipeng',),
 ('Wang Shun',),
 ('Wang Shun',),
 ('Wang Wei',),
 ('Wang Weidong',),
 ('Wang Xiangdang',),
 ('Wang Xiaolong',),
 ('Wang Xin (Ruoxue-)',),
 ('Wang Xin (Ruoxue-)',),
 ('Wang Xueer',),
 ('Wang Yang',),
 ('Wang Yi',),
 ('Wang Yimei',),
 ('Wang Ying',),
 ('Wang Ying',),
 ('Wang Yong',),
 ('Wang Zheng',),
 ('Wang Zhizhi',),
 ('Wei Ning',),
 ('Wei Qiuxiang',),
 ('Wei Qiuyue',),
 ('Wei Yili',),
 ('Wen Yimei',),
 ('Wen Yongyi',),
 ('Weng Xinzhi',),
 ('Wu Chongkui',),
 ('Wu Di',),
 ('Wu Jingyu',),
 ('Wu Liuxi',),
 ('Wu Minxia',),
 ('Wu Minxia',),
 ('Wu Peng',),
 ('Wu Penggen',),
 ('Wu Ritubilige',),
 ('Wu Shugen',),
 ('Wu Wenjuan',),
 ('Wu Yanan',),
 ('Wu You',),
 ('Wu Yuhang',),
 ('Wu Zhiyu',),
 ('Xi Aihua',),
 ('Xian Dongmei',),
 ('Xiao Qin',),
 ('Xiao Qin',),
 ('Xiao Qin',),
 ('Xiao Qin',),
 ('Xiao Qin',),
 ('Xiao Qin',),
 ('Xie Junmin',),
 ('Xie Limei',),
 ('Xie Xingfan',),
 ('Xie Zhongbo',),
 ('Xin Minhong',),
 ('Xin Tong',),
 ('Xin Xin',),
 ('Xing Lin',),
 ('Xiu Xiu',),
 ('Xu Dongxiang',),
 ('Xu Haiyan',),
 ('Xu Jiayu',),
 ('Xu Jiayu',),
 ('Xu Jiayu',),
 ('Xu Li',),
 ('Xu Lijia',),
 ('Xu Linbei',),
 ('Xu Linyin',),
 ('Xu Tianlongzi',),
 ('Xu Tianlongzi',),
 ('Xu Yan',),
 ('Xu Yanwei',),
 ('Xu Yanwei',),
 ('Xu Yaping',),
 ('Xu Yuan',),
 ('Xu Yuhua',),
 ('Xu Yunli',),
 ('Xu Zheng',),
 ('Xue Chen',),
 ('Xue Fei',),
 ('Xue Haifeng',),
 ('Xue Haifeng',),
 ('Xue Ming',),
 ('Xue Ruipeng',),
 ('Yan Liang',),
 ('Yan Meizhu',),
 ('Yan Zi',),
 ('Yan Zi',),
 ('Yan Zibei',),
 ('Yang Hao',),
 ('Yang Jun',),
 ('Yang Mingxia',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wei',),
 ('Yang Wenjun',),
 ('Yang Xiuli',),
 ('Yang Yang',),
 ('Yang Yilin',),
 ('Yang Yilin',),
 ('Yang Yilin',),
 ('Yang Yilin',),
 ('Yang Yilin',),
 ('Yang Yu',),
 ('Yao Ming',),
 ('Ye Qiang',),
 ('Ye Shiwen',),
 ('Ye Shiwen',),
 ('Yi Jianlian',),
 ('Yin Jian',),
 ('Yin Lianchi',),
 ('Yin Lianchi',),
 ('You Meihong',),
 ('Yu Chunyan',),
 ('Yu Dawei',),
 ('Yu Hexin',),
 ('Yu Hexin',),
 ('Yu Hexin',),
 ('Yu Hua',),
 ('Yu Huili',),
 ('Yu Jingyao',),
 ('Yu Lamei',),
 ('Yu Lijun',),
 ('Yu Xinyuan',),
 ('Yu Xinyuan',),
 ('Yu Yang',),
 ('Yu Yang',),
 ('Yu Yang',),
 ('Yu Yanhong',),
 ('Yu Yanli',),
 ('Yuan Wenwei',),
 ('Yuan Zhi',),
 ('Yushan Nijiati',),
 ('Zeng Shaoxuan',),
 ('Zeng Shaoxuan',),
 ('Zhang Ai',),
 ('Zhang Bin',),
 ('Zhang Bin',),
 ('Zhang Dechang',),
 ('Zhang Enjian',),
 ('Zhang Enjian',),
 ('Zhang Geng',),
 ('Zhang Guolin',),
 ('Zhang Hanlan',),
 ('Zhang Hongbo',),
 ('Zhang Ji',),
 ('Zhang Jiewen',),
 ('Zhang Juanjuan',),
 ('Zhang Juanjuan',),
 ('Zhang Lei',),
 ('Zhang Lei',),
 ('Zhang Lei',),
 ('Zhang Lei',),
 ('Zhang Li',),
 ('Zhang Li',),
 ('Zhang Liang',),
 ('Zhang Lifang',),
 ('Zhang Lin',),
 ('Zhang Lin',),
 ('Zhang Lin',),
 ('Zhang Lin',),
 ('Zhang Na',),
 ('Zhang Na',),
 ('Zhang Ning',),
 ('Zhang Peimeng',),
 ('Zhang Peimeng',),
 ('Zhang Peng',),
 ('Zhang Penghui',),
 ('Zhang Qibin',),
 ('Zhang Qingpeng',),
 ('Zhang Shujing',),
 ('Zhang Shunyin',),
 ('Zhang Shuo',),
 ('Zhang Wei',),
 ('Zhang Wenxiu',),
 ('Zhang Xi',),
 ('Zhang Xiangxiang',),
 ('Zhang Xiaohuan',),
 ('Zhang Xiaoni',),
 ('Zhang Xiaoping',),
 ('Zhang Xing',),
 ('Zhang Xingbo',),
 ('Zhang Xinyu',),
 ('Zhang Xinyu',),
 ('Zhang Xiuyun',),
 ('Zhang Yangyang',),
 ('Zhang Yanru',),
 ('Zhang Yawen',),
 ('Zhang Yi',),
 ('Zhang Yimeng',),
 ('Zhang Ying',),
 ('Zhang Yingying',),
 ('Zhang Yingying',),
 ('Zhang Yining',),
 ('Zhang Yining',),
 ('Zhang Yongqiang',),
 ('Zhang Yu',),
 ('Zhang Yufei',),
 ('Zhang Yufeng',),
 ('Zhang Yuhan',),
 ('Zhang Yuhan',),
 ('Zhang Yuhan',),
 ('Zhang Zhilei',),
 ('Zhang Zhiwu',),
 ('Zhao Chengliang',),
 ('Zhao Jing',),
 ('Zhao Jing',),
 ('Zhao Jing',),
 ('Zhao Linquan',),
 ('Zhao Ruirui',),
 ('Zhao Xuri',),
 ('Zhao Yanni',),
 ('Zhao Yinghui',),
 ('Zhao Yudiao',),
 ('Zhao Zhiwen',),
 ('Zhao Zhiwen',),
 ('Zheng Bo',),
 ('Zheng Chuanqi',),
 ('Zheng Jie',),
 ('Zheng Jie',),
 ('Zheng Xingjuan',),
 ('Zheng Zhi',),
 ('Zhong Hongyan',),
 ('Zhong Hongyan',),
 ('Zhong Man',),
 ('Zhong Man',),
 ('Zhong Minwei',),
 ('Zhong Weiping',),
 ('Zhou Chunxiu',),
 ('Zhou Gaoping',),
 ('Zhou Haibin',),
 ('Zhou Hanming',),
 ('Zhou Hanming',),
 ('Zhou Luxin',),
 ('Zhou Min',),
 ('Zhou Min',),
 ('Zhou Peng',),
 ('Zhou Suhong',),
 ('Zhou Wanfeng',),
 ('Zhou Xiaojian',),
 ('Zhou Yafei',),
 ('Zhou Yafei',),
 ('Zhou Yang',),
 ('Zhou Yi',),
 ('Zhou Yilin',),
 ('Zhou Yinan',),
 ('Zhu Fangyu',),
 ('Zhu Guo',),
 ('Zhu Jie',),
 ('Zhu Jun',),
 ('Zhu Menghui',),
 ('Zhu Menghui',),
 ('Zhu Menghui',),
 ('Zhu Qianwei',),
 ('Zhu Qianwei',),
 ('Zhu Qinan',),
 ('Zhu Ting',),
 ('Zhu Wenxin',),
 ('Zhu Xiaolin',),
 ('Zhu Yanmei',),
 ('Zhu Yingwen',),
 ('Zhu Yingwen',),
 ('Zhu Yingwen',),
 ('Zou Kai',),
 ('Zou Kai',),
 ('Zou Kai',),
 ('Zou Kai',),
 ('Zou Shiming',),
 ('Zu Lijun',),
 ('Mads Christian Kruse Andersen',),
 ('Jakob Schitt Andkjr',),
 ('Jakob Schitt Andkjr',),
 ('Jakob Schitt Andkjr',),
 ('Henrik Baltzersen',),
 ('Kasper Bleibach',),
 ('Pernille Blume',),
 ('Pernille Blume',),
 ('Pernille Blume',),
 ('Pernille Blume',),
 ('Lasse Motzkus Boesen',),
 ('Joachim Rietveld Boldsen',),
 ('Sarah Bro',),
 ('Viktor Bregner Bromer',),
 ('Klavs Bruun Jrgensen (-Hrlykke)',),
 ('Chris Boe Christensen',),
 ('Chris Boe Christensen',),
 ('Michael Frk Christensen',),
 ('Lars Roslyng Christiansen',),
 ('Sren Dahl',),
 ('Niels Dall',),
 ('Eskild Balschmidt Ebbesen',),
 ('Thomas Ebert',),
 ('Jens Dyrlv Eriksen',),
 ('Peter Tersgov Flarup',),
 ('Lotte Friis',),
 ('Lotte Friis',),
 ('Lotte Friis',),
 ('Lotte Friis',),
 ('Lotte Friis',),
 ('Jakob Diemer Fuglsang',),
 ('Mads Glsner',),
 ('Mads Glsner',),
 ('Mads Glsner',),
 ('Anders Christian Golding',),
 ('Henriette Engel Hansen',),
 ('Martin Lundgaard Hansen',),
 ('Mikkel Hansen',),
 ('Lars Andreas Helgstrand',),
 ('Lars Andreas Helgstrand',),
 ('Rasmus Henning',),
 ('Peter Henriksen',),
 ('Julie Hjorth-Hansen (-Hjorth-Nielsen)',),
 ('Julie Hjorth-Hansen (-Hjorth-Nielsen)',),
 ('Bettina Honore',),
 ('Peter Heg Gade Birkeholm Christensen',),
 ('Jonas Hgh Christensen',),
 ('Kasper Hvidt',),
 ('Anton rskov Ipsen',),
 ('Anton rskov Ipsen',),
 ('Louise Mai Jansen',),
 ('Louise Mai Jansen',),
 ('Jesper Haandbk Jensen',),
 ('Julie Kepp Jensen',),
 ('Morten Jensen',),
 ('Peter Jensen',),
 ('Anne Jensen-van Olst',),
 ('Anne Jensen-van Olst',),
 ('Pl Vitalis Joensen',),
 ('Kenneth Jonassen',),
 ('Casper Jrgensen',),
 ('Lars Troels Jrgensen',),
 ('Morten Jrgensen',),
 ('Kamilla Rytter Juhl',),
 ('Kamilla Rytter Juhl',),
 ('Martin Kirketerp Ibsen',),
 ('Kim Wraae Knudsen',),
 ('Kim Wraae Knudsen',),
 ('Daniel Adelhard Kreutzfeldt',),
 ('Lena Frier Kristiansen',),
 ('Thomas Morsing Larsen',),
 ('Louise Klingenberg Laursen',),
 ('Thomas Laybourn',),
 ('Anders Lie Nielsen',),
 ('Hans Ottar Lindberg',),
 ('Jens-Erik Madsen',),
 ('Mark Overgaard Madsen',),
 ('Michael John Maze',),
 ('Michael Mrkv (-Christiansen)',),
 ('Michael Mrkv (-Christiansen)',),
 ('Kasper Nielsen',),
 ('Klaus Nielsen',),
 ('Mie stergaard Nielsen',),
 ('Mie stergaard Nielsen',),
 ('Mie stergaard Nielsen',),
 ('Morten lgaard Nielsen',),
 ('Jesper Nddesbo',),
 ('Anders Daniel Nyblom',),
 ('Anders Nyholm-Pedersen',),
 ('Joachim Brchner Olsen',),
 ('Katrin Olsen',),
 ('Micha Kathrine stergaard Jensen',),
 ('Micha Kathrine stergaard Jensen',),
 ('Micha Kathrine stergaard Jensen',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Jeanette Ottesen Gray',),
 ('Lars Hjer Paaske',),
 ('Rikke Mller Pedersen',),
 ('Rikke Mller Pedersen',),
 ('Rikke Mller Pedersen',),
 ('Jonas Klds Poulsen',),
 ('Ren Holten Poulsen',),
 ('Ren Holten Poulsen',),
 ('Rasmus Nicolai Quist Hansen',),
 ('Alex Nicki Rasmussen',),
 ('Alex Nicki Rasmussen',),
 ('Jonas Rasmussen',),
 ('Juliane Elander Rasmussen',),
 ('Mads Reinholdt Rasmussen (-Kirke)',),
 ('Tine Rasmussen Baun',),
 ('Jon Rhauge Rud',),
 ('Jon Rhauge Rud',),
 ('Christina Illum Scherwin',),
 ('Trine Schmidt',),
 ('Daniel Skaaning',),
 ('Kasper Sndergaard Sarup',),
 ('Amanda Srensen',),
 ('Chris Anker Srensen',),
 ('Chris Anker Srensen',),
 ('Nicki Srensen',),
 ('Bo Dybdal Spellerberg',),
 ('Brian Bach Vandborg',),
 ('Brian Bach Vandborg',),
 ('Linda Melanie Villumsen Serup',),
 ('Linda Melanie Villumsen Serup',),
 ('Jonas Warrer',),
 ('Magnus Westermann',),
 ('Caroline Wozniacki',),
 ('Nathalie Xenia Margareta Benedikte zu Sayn-Wittgenstein-Berleburg',),
 ('Nathalie Xenia Margareta Benedikte zu Sayn-Wittgenstein-Berleburg',),
 ('Sharnol Leonard Adriana',),
 ('Marilyn Agliotti',),
 ('Olaf van Andel',),
 ('Indra Angad-Gaur',),
 ('Ryan Guno Babel',),
 ('Otman Bakkal',),
 ('Roy Johannes Henricus Beerens',),
 ('Dennis Bekkers',),
 ('Chantal Herlindes Julitte Beltman',),
 ('David Franciscus Johan Bergman',),
 ('Sander Johannes Gerardes Berk',),
 ('Lobke Berkhout',),
 ('Annemieke Marileen Bes',),
 ('Rogier Blink',),
 ('Nomi Boekel',),
 ('Thomas Lodewijk Boerma',),
 ('Emiel Nicolaas Paulus Boersma',),
 ('Minke Gertine Booij',),
 ('Mitchell Jay "Mitch" Booth',),
 ('Theo Bos',),
 ('Theo Bos',),
 ('Theo Bos',),
 ('Marcelien Bos-de Koning',),
 ('Edith Bosch',),
 ('Casper Bouman',),
 ('Robert Adriaan Bouten',),
 ('Leon Boyd',),
 ('Bart Jan-Baptist Marie Brentjens',),
 ('Matthijs Christian Brouwer',),
 ('Ronald Leendert Brouwer',),
 ('Maarten Brzoskowski',),
 ('Maarten Brzoskowski',),
 ('Frederike Jacobie "Mieke" Cabout',),
 ('Geert Anne Cirkel',),
 ('Stef Marie Michel Clement',),
 ('Stef Marie Michel Clement',),
 ('Robbie "Rob" Cordemans',),
 ('Kalle Kristian Coster',),
 ('Sven Erik Coster',),
 ('Danille de Bruijn',),
 ('Yurendell Eithel de Caster',),
 ('Eva Roma Maria de Goede',),
 ('Jonathan Alexander de Guzmn',),
 ('Annemiek Nicolien de Haan',),
 ('Sidney de Jong',),
 ('Saskia Klazina de Jonge',),
 ('Teun Floris de Nooijer',),
 ('Daisy de Peinder',),
 ('Lisanne Freya de Roever',),
 ('Kristi Lynn de Vries',),
 ('Jan Robert de Wilde',),
 ('Femke Pauline Dekker',),
 ('Inge Dekker',),
 ('Inge Dekker',),
 ('Inge Dekker',),
 ('Inge Dekker',),
 ('Inge Dekker',),
 ('Inge Dekker',),
 ('Jeroen Petrus Maria Delme',),
 ('Geert Jan Marie "Geert-Jan" Derikx',),
 ...]

#### Problem 4
Display the names of all countries that have won more than 50 medals in a single year.

In [64]:
%%sql

SELECT country, Year, COUNT(Medal) AS 'num_medal' 
FROM olympics_data
    WHERE Medal IS NOT NULL 
    AND country IS NOT NULL
    GROUP BY Year, country
    HAVING COUNT(Medal)> 50

 * mysql+pymysql://root:***@localhost:3306/olympics

[('China', 1992, 460),
 ('China', 2012, 534),
 ('China', 2000, 460),
 ('China', 2004, 560),
 ('China', 2016, 546),
 ('China', 1996, 470),
 ('China', 2008, 777),
 ('China', 1984, 410),
 ('China', 1936, 65),
 ('China', 1988, 518),
 ('Denmark', 1920, 246),
 ('Denmark', 1948, 251),
 ('Denmark', 1952, 201),
 ('Denmark', 2000, 124),
 ('Denmark', 1908, 107),
 ('Denmark', 1972, 155),
 ('Denmark', 1928, 122),
 ('Denmark', 1996, 145),
 ('Denmark', 1912, 233),
 ('Denmark', 1956, 51),
 ('Denmark', 1932, 69),
 ('Denmark', 1936, 173),
 ('Denmark', 1992, 144),
 ('Denmark', 2016, 143),
 ('Denmark', 1960, 109),
 ('Denmark', 2004, 115),
 ('Denmark', 1924, 146),
 ('Denmark', 1964, 71),
 ('Denmark', 1976, 81),
 ('Denmark', 1968, 93),
 ('Denmark', 2008, 108),
 ('Denmark', 2012, 149),
 ('Denmark', 1984, 74),
 ('Denmark', 1980, 60),
 ('Denmark', 1988, 130),
 ('Netherlands', 1932, 67),
 ('Netherlands', 1984, 185),
 ('Netherlands', 1988, 202),
 ('Netherlands', 1996, 290),
 ('Netherlands', 2000, 285),
 ('Netherlands', 2016, 329),
 ('Netherlands', 1976, 175),
 ('Netherlands', 2012, 222),
 ('Netherlands', 1968, 140),
 ('Netherlands', 1980, 112),
 ('Netherlands', 1924, 238),
 ('Netherlands', 1928, 369),
 ('Netherlands', 2004, 264),
 ('Netherlands', 2008, 283),
 ('Netherlands', 1972, 199),
 ('Netherlands', 1952, 180),
 ('Netherlands', 1960, 160),
 ('Netherlands', 1964, 158),
 ('Netherlands', 1948, 187),
 ('Netherlands', 1992, 257),
 ('Netherlands', 1936, 209),
 ('Netherlands', 1908, 214),
 ('Netherlands', 1920, 213),
 ('Netherlands', 1900, 73),
 ('Finland', 1952, 412),
 ('Finland', 2000, 88),
 ('Finland', 1996, 105),
 ('Finland', 1912, 233),
 ('Finland', 1920, 136),
 ('Finland', 1924, 253),
 ('Finland', 1948, 215),
 ('Finland', 1992, 130),
 ('Finland', 1936, 186),
 ('Finland', 1932, 66),
 ('Finland', 1928, 132),
 ('Finland', 1980, 125),
 ('Finland', 1960, 219),
 ('Finland', 1968, 126),
 ('Finland', 1988, 101),
 ('Finland', 2004, 67),
 ('Finland', 1972, 133),
 ('Finland', 1976, 108),
 ('Finland', 1984, 107),
 ('Finland', 2008, 70),
 ('Finland', 2012, 69),
 ('Finland', 1964, 151),
 ('Finland', 1956, 147),
 ('Finland', 1908, 94),
 ('Finland', 2016, 67),
 ('Norway', 2008, 102),
 ('Norway', 2000, 115),
 ('Norway', 2004, 60),
 ('Norway', 1920, 267),
 ('Norway', 1968, 86),
 ('Norway', 1972, 161),
 ('Norway', 1912, 263),
 ('Norway', 1996, 116),
 ('Norway', 1992, 114),
 ('Norway', 1936, 84),
 ('Norway', 1948, 97),
 ('Norway', 1952, 190),
 ('Norway', 1924, 104),
 ('Norway', 1928, 74),
 ('Norway', 2016, 77),
 ('Norway', 1984, 132),
 ('Norway', 1988, 79),
 ('Norway', 2012, 69),
 ('Norway', 1908, 103),
 ('Norway', 1976, 79),
 ('Romania', 2016, 121),
 ('Romania', 1936, 118),
 ('Romania', 1952, 241),
 ('Romania', 2008, 172),
 ('Romania', 1976, 255),
 ('Romania', 2012, 155),
 ('Romania', 1984, 193),
 ('Romania', 1972, 258),
 ('Romania', 2000, 252),
 ('Romania', 1980, 339),
 ('Romania', 1968, 100),
 ('Romania', 1996, 284),
 ('Romania', 1956, 103),
 ('Romania', 1960, 156),
 ('Romania', 1964, 232),
 ('Romania', 1988, 172),
 ('Romania', 1992, 306),
 ('Romania', 2004, 193),
 ('Estonia', 2008, 53),
 ('Estonia', 1996, 52),
 ('France', 2012, 426),
 ('France', 1976, 302),
 ('France', 1956, 227),
 ('France', 2008, 448),
 ('France', 2016, 512),
 ('France', 2004, 461),
 ('France', 1952, 408),
 ('France', 1984, 354),
 ('France', 1968, 311),
 ('France', 1996, 453),
 ('France', 1988, 413),
 ('France', 1972, 356),
 ('France', 1900, 1034),
 ('France', 1924, 555),
 ('France', 1912, 232),
 ('France', 1948, 432),
 ('France', 1992, 486),
 ('France', 1960, 363),
 ('France', 1928, 369),
 ('France', 1932, 134),
 ('France', 2000, 470),
 ('France', 1980, 200),
 ('France', 1964, 214),
 ('France', 1920, 452),
 ('France', 1908, 309),
 ('France', 1936, 303),
 ('Morocco', 2012, 67),
 ('Morocco', 2000, 55),
 ('Morocco', 1960, 111),
 ('Morocco', 2004, 57),
 ('Morocco', 2016, 52),
 ('Spain', 2016, 363),
 ('Spain', 2008, 355),
 ('Spain', 1996, 384),
 ('Spain', 1976, 160),
 ('Spain', 1980, 211),
 ('Spain', 1984, 257),
 ('Spain', 2004, 423),
 ('Spain', 2000, 431),
 ('Spain', 1992, 537),
 ('Spain', 1988, 317),
 ('Spain', 2012, 339),
 ('Spain', 1920, 111),
 ('Spain', 1948, 84),
 ('Spain', 1964, 67),
 ('Spain', 1968, 137),
 ('Spain', 1960, 238),
 ('Spain', 1928, 106),
 ('Spain', 1924, 151),
 ('Spain', 1972, 162),
 ('Egypt', 2000, 103),
 ('Egypt', 1964, 83),
 ('Egypt', 1952, 196),
 ('Egypt', 2004, 104),
 ('Egypt', 2012, 132),
 ('Egypt', 2008, 116),
 ('Egypt', 2016, 137),
 ('Egypt', 1992, 83),
 ('Egypt', 1948, 166),
 ('Egypt', 1984, 148),
 ('Egypt', 1988, 59),
 ('Egypt', 1936, 66),
 ('Iran', 2012, 57),
 ('Iran', 2016, 67),
 ('Iran', 1976, 104),
 ('Iran', 2008, 55),
 ('Iran', 1972, 56),
 ('Iran', 1964, 96),
 ('Bulgaria', 1988, 281),
 ('Bulgaria', 1956, 82),
 ('Bulgaria', 1960, 183),
 ('Bulgaria', 1976, 254),
 ('Bulgaria', 1980, 397),
 ('Bulgaria', 1964, 116),
 ('Bulgaria', 1968, 189),
 ('Bulgaria', 2012, 75),
 ('Bulgaria', 2016, 58),
 ('Bulgaria', 1992, 236),
 ('Bulgaria', 2004, 119),
 ('Bulgaria', 2008, 87),
 ('Bulgaria', 1972, 226),
 ('Bulgaria', 1996, 181),
 ('Bulgaria', 2000, 150),
 ('Bulgaria', 1936, 84),
 ('Bulgaria', 1952, 179),
 ('Italy', 2016, 399),
 ('Italy', 2012, 382),
 ('Italy', 2008, 459),
 ('Italy', 1936, 331),
 ('Italy', 1988, 374),
 ('Italy', 1996, 460),
 ('Italy', 2000, 457),
 ('Italy', 1984, 368),
 ('Italy', 1992, 431),
 ('Italy', 1980, 203),
 ('Italy', 1972, 345),
 ('Italy', 1948, 303),
 ('Italy', 1908, 97),
 ('Italy', 2004, 474),
 ('Italy', 1964, 256),
 ('Italy', 1952, 376),
 ('Italy', 1928, 262),
 ('Italy', 1932, 149),
 ('Italy', 1912, 96),
 ('Italy', 1968, 268),
 ('Italy', 1976, 312),
 ('Italy', 1924, 327),
 ('Italy', 1960, 402),
 ('Italy', 1920, 291),
 ('Italy', 1956, 207),
 ('Azerbaijan', 2016, 69),
 ('Azerbaijan', 2012, 59),
 ('Russia', 2008, 600),
 ('Russia', 2012, 549),
 ('Russia', 2004, 593),
 ('Russia', 2016, 406),
 ('Russia', 2000, 602),
 ('Russia', 1912, 266),
 ('Russia', 1996, 552),
 ('Argentina', 2000, 165),
 ('Argentina', 2012, 148),
 ('Argentina', 1968, 132),
 ('Argentina', 1972, 123),
 ('Argentina', 1976, 106),
 ('Argentina', 1960, 116),
 ('Argentina', 1964, 148),
 ('Argentina', 2008, 145),
 ('Argentina', 1952, 174),
 ('Argentina', 2016, 232),
 ('Argentina', 1948, 295),
 ('Argentina', 1988, 134),
 ('Argentina', 1984, 115),
 ('Argentina', 1992, 111),
 ('Argentina', 1936, 68),
 ('Argentina', 1924, 109),
 ('Argentina', 1996, 221),
 ('Argentina', 2004, 179),
 ('Argentina', 1928, 98),
 ('Cuba', 2000, 271),
 ('Cuba', 1992, 196),
 ('Cuba', 2012, 118),
 ('Cuba', 1976, 194),
 ('Cuba', 1980, 288),
 ('Cuba', 1972, 201),
 ('Cuba', 2008, 171),
 ('Cuba', 1948, 112),
 ('Cuba', 1952, 57),
 ('Cuba', 1996, 178),
 ('Cuba', 2004, 177),
 ('Cuba', 2016, 143),
 ('Cuba', 1968, 227),
 ('Cuba', 1964, 76),
 ('Belarus', 2004, 192),
 ('Belarus', 2008, 237),
 ('Belarus', 2016, 142),
 ('Belarus', 1996, 259),
 ('Belarus', 2000, 231),
 ('Belarus', 2012, 185),
 ('Greece', 2004, 499),
 ('Greece', 1996, 180),
 ('Greece', 2000, 175),
 ('Greece', 2008, 176),
 ('Greece', 2012, 115),
 ('Greece', 2016, 104),
 ('Greece', 1896, 148),
 ('Greece', 1988, 72),
 ('Greece', 1984, 73),
 ('Greece', 1924, 79),
 ('Greece', 1920, 98),
 ('Greece', 1912, 77),
 ('Greece', 1960, 59),
 ('Greece', 1936, 64),
 ('Greece', 1948, 96),
 ('Greece', 1952, 54),
 ('Greece', 1992, 76),
 ('Greece', 1972, 66),
 ('Cameroon', 1984, 56),
 ('Turkey', 1996, 61),
 ('Turkey', 2004, 74),
 ('Turkey', 2008, 71),
 ('Turkey', 1948, 87),
 ('Turkey', 1952, 58),
 ('Turkey', 2000, 67),
 ('Turkey', 2016, 119),
 ('Turkey', 1936, 62),
 ('Turkey', 1988, 51),
 ('Turkey', 1960, 58),
 ('Turkey', 2012, 119),
 ('Turkey', 1984, 62),
 ('Turkey', 1992, 54),
 ('Chile', 1984, 64),
 ('Chile', 1948, 72),
 ('Chile', 1936, 56),
 ('Chile', 1952, 82),
 ('Chile', 2000, 58),
 ('Mexico', 2000, 98),
 ('Mexico', 1968, 446),
 ('Mexico', 2016, 139),
 ('Mexico', 1996, 111),
 ('Mexico', 2004, 137),
 ('Mexico', 1984, 155),
 ('Mexico', 1992, 140),
 ('Mexico', 2008, 103),
 ('Mexico', 2012, 119),
 ('Mexico', 1948, 149),
 ('Mexico', 1988, 144),
 ('Mexico', 1960, 110),
 ('Mexico', 1964, 128),
 ('Mexico', 1972, 281),
 ('Mexico', 1976, 137),
 ('Mexico', 1932, 100),
 ('Mexico', 1952, 85),
 ('Mexico', 1980, 74),
 ('USA', 2004, 726),
 ('USA', 1928, 392),
 ('USA', 2016, 719),
 ('USA', 1900, 135),
 ('USA', 2008, 763),
 ('USA', 2000, 764),
 ('USA', 2012, 689),
 ('USA', 1904, 1109),
 ('USA', 1932, 544),
 ('USA', 1996, 839),
 ('USA', 1984, 693),
 ('USA', 1972, 578),
 ('USA', 1976, 554),
 ('USA', 1988, 715),
 ('USA', 1920, 473),
 ('USA', 1936, 472),
 ('USA', 1912, 364),
 ('USA', 1908, 218),
 ('USA', 1992, 734),
 ('USA', 1952, 451),
 ('USA', 1948, 424),
 ('USA', 1960, 428),
 ('USA', 1968, 529),
 ('USA', 1956, 443),
 ('USA', 1964, 492),
 ('USA', 1924, 459),
 ('Russia', 1964, 463),
 ('Russia', 1980, 660),
 ('Russia', 1972, 531),
 ('Russia', 1988, 647),
 ('Russia', 1960, 414),
 ('Russia', 1976, 574),
 ('Russia', 1968, 471),
 ('Russia', 1956, 411),
 ('Russia', 1952, 451),
 ('Hungary', 1992, 351),
 ('Hungary', 1936, 335),
 ('Hungary', 1988, 315),
 ('Hungary', 1924, 140),
 ('Hungary', 1912, 207),
 ('Hungary', 1952, 345),
 ('Hungary', 1972, 367),
 ('Hungary', 1996, 315),
 ('Hungary', 1964, 319),
 ('Hungary', 2000, 238),
 ('Hungary', 2004, 258),
 ('Hungary', 1960, 312),
 ('Hungary', 1968, 303),
 ('Hungary', 1980, 392),
 ('Hungary', 1976, 288),
 ('Hungary', 1948, 222),
 ('Hungary', 2012, 201),
 ('Hungary', 2016, 204),
 ('Hungary', 1908, 107),
 ('Hungary', 2008, 216),
 ('Hungary', 1956, 197),
 ('Hungary', 1932, 94),
 ('Hungary', 1928, 188),
 ('Nigeria', 1988, 86),
 ('Nigeria', 2012, 58),
 ('Nigeria', 2016, 77),
 ('Nigeria', 2008, 89),
 ('Nigeria', 1996, 84),
 ('Nigeria', 1992, 72),
 ('Nigeria', 1980, 56),
 ('Nigeria', 2000, 100),
 ('Nigeria', 2004, 79),
 ('Algeria', 2016, 74),
 ('Algeria', 1980, 63),
 ('Algeria', 2008, 57),
 ('Algeria', 2000, 51),
 ('Algeria', 2004, 71),
 ('Kuwait', 1980, 67),
 ('Pakistan', 1960, 53),
 ('Pakistan', 1952, 51),
 ('Pakistan', 1956, 79),
 ('Syria', 1960, 123),
 ('Malaysia', 2000, 55),
 ('Malaysia', 1964, 81),
 ('Malaysia', 1972, 57),
 ('Germany', 1900, 103),
 ('Germany', 1928, 369),
 ('Germany', 2008, 558),
 ('Germany', 2016, 536),
 ('Germany', 1912, 312),
 ('Germany', 2000, 567),
 ('Germany', 1996, 626),
 ('Germany', 1908, 145),
 ('Germany', 1936, 543),
 ('Germany', 2004, 592),
 ('Germany', 1992, 653),
 ('Germany', 2012, 510),
 ('Germany', 1952, 458),
 ('Germany', 1960, 425),
 ('Germany', 1964, 478),
 ('Germany', 1932, 177),
 ('Germany', 1956, 261),
 ('Germany', 1896, 94),
 ('Germany', 1904, 55),
 ('Canada', 1996, 408),
 ('Canada', 2000, 422),
 ('Canada', 1976, 531),
 ('Canada', 2008, 449),
 ('Canada', 1984, 572),
 ('Canada', 2012, 354),
 ('Canada', 2016, 405),
 ('Canada', 1952, 154),
 ('Canada', 1972, 344),
 ('Canada', 1936, 164),
 ('Canada', 1928, 107),
 ('Canada', 1960, 140),
 ('Canada', 1992, 445),
 ('Canada', 1988, 503),
 ('Canada', 1964, 194),
 ('Canada', 2004, 391),
 ('Canada', 1904, 62),
 ('Canada', 1908, 146),
 ('Canada', 1968, 291),
 ('Canada', 1932, 149),
 ('Canada', 1924, 83),
 ('Canada', 1956, 150),
 ('Canada', 1948, 188),
 ('Canada', 1912, 60),
 ('Canada', 1920, 85),
 ('Ireland', 2016, 93),
 ('Ireland', 1948, 82),
 ('Ireland', 1996, 99),
 ('Ireland', 2012, 76),
 ('Ireland', 2004, 55),
 ('Ireland', 2008, 63),
 ('Ireland', 1960, 63),
 ('Ireland', 1968, 57),
 ('Ireland', 1972, 84),
 ('Ireland', 1924, 60),
 ('Ireland', 1992, 77),
 ('Ireland', 1980, 57),
 ('Ireland', 2000, 76),
 ('Ireland', 1976, 59),
 ('Ireland', 1988, 78),
 ('Ireland', 1984, 55),
 ('Australia', 2008, 570),
 ('Australia', 2012, 514),
 ('Australia', 2000, 788),
 ('Australia', 2004, 601),
 ('Australia', 2016, 518),
 ('Australia', 1956, 412),
 ('Australia', 1992, 390),
 ('Australia', 1976, 274),
 ('Australia', 1984, 337),
 ('Australia', 1988, 339),
 ('Australia', 1996, 550),
 ('Australia', 1948, 103),
 ('Australia', 1952, 140),
 ('Australia', 1964, 392),
 ('Australia', 1972, 266),
 ('Australia', 1980, 190),
 ('Australia', 1960, 280),
 ('Australia', 1968, 224),
 ('Australia', 1924, 60),
 ('South Africa', 2008, 179),
 ('South Africa', 1956, 90),
 ('South Africa', 2000, 161),
 ('South Africa', 1992, 141),
 ('South Africa', 2016, 155),
 ('South Africa', 1996, 111),
 ('South Africa', 1952, 109),
 ('South Africa', 2012, 145),
 ('South Africa', 1960, 72),
 ('South Africa', 2004, 128),
 ('South Africa', 1920, 97),
 ('South Africa', 1912, 56),
 ('Tunisia', 2012, 87),
 ('Tunisia', 1996, 52),
 ('Tunisia', 2016, 65),
 ('Tunisia', 1960, 56),
 ('Tunisia', 2004, 64),
 ('Belgium', 2016, 138),
 ('Belgium', 1956, 82),
 ('Belgium', 1960, 150),
 ('Belgium', 1924, 232),
 ('Belgium', 1928, 240),
 ('Belgium', 1936, 181),
 ('Belgium', 1948, 180),
 ('Belgium', 1920, 518),
 ('Belgium', 1912, 72),
 ('Belgium', 2012, 142),
 ('Belgium', 2008, 112),
 ('Belgium', 1976, 149),
 ('Belgium', 1980, 84),
 ('Belgium', 1952, 184),
 ('Belgium', 1964, 74),
 ('Belgium', 1984, 86),
 ('Belgium', 1908, 99),
 ('Belgium', 1988, 85),
 ('Belgium', 1992, 103),
 ('Belgium', 1996, 81),
 ('Belgium', 2000, 94),
 ('Belgium', 1968, 106),
 ('Belgium', 1972, 106),
 ('Belgium', 1900, 100),
 ('Belgium', 2004, 70),
 ('Kazakhstan', 2016, 123),
 ('Kazakhstan', 2008, 146),
 ('Kazakhstan', 1996, 142),
 ('Kazakhstan', 2012, 132),
 ('Kazakhstan', 2004, 130),
 ('Kazakhstan', 2000, 158),
 ('India', 1984, 53),
 ('India', 1988, 55),
 ('India', 1992, 61),
 ('India', 1996, 54),
 ('India', 2004, 81),
 ('India', 2008, 67),
 ('India', 2016, 130),
 ('India', 1948, 89),
 ('India', 1980, 78),
 ('India', 1956, 79),
 ('India', 1964, 111),
 ('India', 2000, 70),
 ('India', 1952, 94),
 ('India', 2012, 95),
 ('Syria', 1980, 71),
 ('Indonesia', 2000, 54),
 ('Indonesia', 1992, 51),
 ('Philippines', 1968, 89),
 ('Philippines', 1972, 79),
 ('Philippines', 1964, 70),
 ('Uzbekistan', 1996, 95),
 ('Uzbekistan', 2000, 85),
 ('Uzbekistan', 2012, 56),
 ('Uzbekistan', 2016, 80),
 ('Uzbekistan', 2004, 79),
 ('Uzbekistan', 2008, 69),
 ('Kyrgyzstan', 2000, 71),
 ('Kyrgyzstan', 1996, 53),
 ('Russia', 1992, 650),
 ('Japan', 1936, 310),
 ('Japan', 1960, 278),
 ('Japan', 1992, 392),
 ('Japan', 1972, 293),
 ('Japan', 1968, 289),
 ('Japan', 1976, 328),
 ('Japan', 2000, 363),
 ('Japan', 2008, 457),
 ('Japan', 1996, 448),
 ('Japan', 1984, 365),
 ('Japan', 1988, 412),
 ('Japan', 2004, 414),
 ('Japan', 2012, 399),
 ('Japan', 1964, 456),
 ('Japan', 2016, 436),
 ('Japan', 1956, 222),
 ('Japan', 1928, 56),
 ('Japan', 1932, 198),
 ('Japan', 1952, 133),
 ('Switzerland', 1924, 260),
 ('Switzerland', 1928, 220),
 ('Switzerland', 2016, 152),
 ('Switzerland', 2012, 126),
 ('Switzerland', 1984, 245),
 ('Switzerland', 1920, 126),
 ('Switzerland', 1948, 278),
 ('Switzerland', 1936, 290),
 ('Switzerland', 1988, 151),
 ('Switzerland', 1976, 101),
 ('Switzerland', 1992, 171),
 ('Switzerland', 1972, 265),
 ('Switzerland', 1980, 86),
 ('Switzerland', 1960, 221),
 ('Switzerland', 1964, 129),
 ('Switzerland', 1952, 251),
 ('Switzerland', 2004, 138),
 ('Switzerland', 1968, 155),
 ('Switzerland', 1996, 172),
 ('Switzerland', 2000, 138),
 ('Switzerland', 2008, 116),
 ('Switzerland', 1900, 52),
 ('Brazil', 1972, 104),
 ('Brazil', 1976, 89),
 ('Brazil', 2016, 583),
 ('Brazil', 2004, 318),
 ('Brazil', 1984, 197),
 ('Brazil', 1988, 233),
 ('Brazil', 2012, 306),
 ('Brazil', 1952, 119),
 ('Brazil', 1964, 65),
 ('Brazil', 1980, 149),
 ('Brazil', 1992, 233),
 ('Brazil', 1996, 251),
 ('Brazil', 2000, 236),
 ('Brazil', 2008, 338),
 ('Brazil', 1936, 94),
 ('Brazil', 1968, 89),
 ('Brazil', 1948, 105),
 ('Brazil', 1956, 63),
 ('Brazil', 1960, 86),
 ('Brazil', 1932, 67),
 ('Germany', 1972, 1041),
 ('Germany', 1988, 918),
 ('Germany', 1976, 859),
 ('Germany', 1980, 495),
 ('Germany', 1968, 778),
 ('Israel', 1984, 65),
 ('Israel', 2016, 59),
 ('Israel', 2012, 56),
 ('Israel', 2000, 58),
 ('Israel', 2008, 60),
 ('Uruguay', 1948, 79),
 ('Sweden', 1912, 714),
 ('Sweden', 1988, 251),
 ('Sweden', 1948, 223),
 ('Sweden', 1952, 355),
 ('Sweden', 2000, 198),
 ('Sweden', 2004, 157),
 ('Sweden', 2008, 169),
 ('Sweden', 1920, 404),
 ('Sweden', 1960, 258),
 ('Sweden', 1964, 175),
 ('Sweden', 1928, 139),
 ('Sweden', 1980, 201),
 ('Sweden', 1936, 206),
 ('Sweden', 1908, 275),
 ('Sweden', 2012, 168),
 ('Sweden', 1924, 256),
 ('Sweden', 1992, 252),
 ('Sweden', 1984, 254),
 ('Sweden', 1932, 106),
 ('Sweden', 1956, 186),
 ('Sweden', 2016, 186),
 ('Sweden', 1968, 186),
 ('Sweden', 1996, 233),
 ('Sweden', 1972, 186),
 ('Sweden', 1976, 163),
 ('Kenya', 2016, 80),
 ('Kenya', 1988, 88),
 ('Kenya', 1984, 67),
 ('Kenya', 1992, 55),
 ('Kenya', 1996, 54),
 ('Kenya', 1972, 69),
 ('Kenya', 2012, 51),
 ('Kenya', 2000, 59),
 ('UK', 1928, 317),
 ('UK', 1936, 250),
 ('UK', 1976, 353),
 ('UK', 1980, 328),
 ('UK', 1920, 345),
 ('UK', 1924, 423),
 ('UK', 1912, 461),
 ('UK', 1968, 328),
 ('UK', 1972, 433),
 ('UK', 2012, 684),
 ('UK', 2000, 415),
 ('UK', 2008, 420),
 ('UK', 2004, 360),
 ('UK', 1992, 512),
 ('UK', 1908, 964),
 ('UK', 1984, 509),
 ('UK', 1988, 472),
 ('UK', 2016, 478),
 ('UK', 1960, 389),
 ('UK', 1964, 301),
 ('UK', 1948, 528),
 ('UK', 1996, 391),
 ('UK', 1932, 142),
 ('UK', 1952, 401),
 ('UK', 1956, 283),
 ('UK', 1900, 145),
 ('Poland', 1980, 418),
 ('Poland', 1924, 100),
 ('Poland', 1992, 263),
 ('Poland', 1972, 418),
 ('Poland', 1976, 286),
 ('Poland', 1948, 52),
 ('Poland', 2008, 316),
 ('Poland', 2012, 256),
 ('Poland', 1952, 248),
 ('Poland', 1960, 307),
 ('Poland', 1936, 167),
 ('Poland', 1968, 296),
 ('Poland', 2016, 289),
 ('Poland', 1964, 240),
 ('Poland', 1928, 115),
 ('Poland', 2004, 224),
 ('Poland', 2000, 240),
 ('Poland', 1988, 192),
 ('Poland', 1996, 207),
 ('Poland', 1956, 118),
 ('Poland', 1932, 63),
 ('Slovenia', 2000, 90),
 ('Slovenia', 2012, 78),
 ('Slovenia', 2004, 102),
 ('Slovenia', 2016, 70),
 ('Slovenia', 2008, 73),
 ('New Zealand', 1956, 57),
 ('New Zealand', 1976, 98),
 ('New Zealand', 1984, 162),
 ('New Zealand', 2004, 184),
 ('New Zealand', 2008, 201),
 ('New Zealand', 2012, 204),
 ('New Zealand', 2016, 232),
 ('New Zealand', 2000, 177),
 ('New Zealand', 1988, 112),
 ('New Zealand', 1992, 175),
 ('New Zealand', 1996, 129),
 ('New Zealand', 1964, 88),
 ('New Zealand', 1968, 65),
 ('New Zealand', 1972, 112),
 ('Portugal', 1988, 91),
 ('Portugal', 1992, 115),
 ('Portugal', 1996, 131),
 ('Portugal', 2008, 87),
 ('Portugal', 2012, 98),
 ('Portugal', 2016, 106),
 ('Portugal', 1960, 109),
 ('Portugal', 2004, 93),
 ('Portugal', 1952, 155),
 ('Portugal', 2000, 64),
 ('Portugal', 1948, 65),
 ('Venezuela', 1996, 53),
 ('Venezuela', 2008, 126),
 ('Venezuela', 2016, 105),
 ('Venezuela', 2012, 85),
 ('Venezuela', 2000, 65),
 ('Venezuela', 2004, 53),
 ('Venezuela', 1960, 54),
 ('Venezuela', 1952, 63),
 ('Venezuela', 1976, 56),
 ('Colombia', 2012, 120),
 ('Colombia', 2016, 157),
 ('Colombia', 1992, 61),
 ('Colombia', 1972, 75),
 ('Colombia', 1988, 57),
 ('Colombia', 2008, 90),
 ('Colombia', 2004, 71),
 ('Colombia', 1996, 62),
 ('Colombia', 1968, 70),
 ('Colombia', 2000, 54),
 ('Germany', 1984, 571),
 ('El Salvador', 1968, 104),
 ('Puerto Rico', 1992, 101),
 ('Puerto Rico', 1988, 56),
 ('Puerto Rico', 1996, 91),
 ('Puerto Rico', 1968, 99),
 ('Puerto Rico', 1984, 58),
 ('Puerto Rico', 2004, 52),
 ('Puerto Rico', 1972, 60),
 ('Puerto Rico', 1976, 112),
 ('Czech Republic', 1976, 251),
 ('Czech Republic', 1980, 317),
 ('Czech Republic', 1988, 226),
 ('Czech Republic', 1992, 269),
 ('Czech Republic', 1968, 203),
 ('Czech Republic', 1972, 274),
 ('Czech Republic', 1964, 187),
 ('Czech Republic', 1924, 241),
 ('Czech Republic', 1956, 161),
 ('Czech Republic', 1928, 147),
 ('Czech Republic', 1920, 182),
 ('Czech Republic', 1952, 218),
 ('Czech Republic', 1936, 286),
 ('Czech Republic', 1948, 151),
 ('Czech Republic', 1960, 202),
 ('Luxembourg', 1928, 104),
 ('Luxembourg', 1924, 122),
 ('Luxembourg', 1960, 117),
 ('Luxembourg', 1948, 115),
 ('Luxembourg', 1952, 101),
 ('Luxembourg', 1936, 115),
 ('Jamaica', 1984, 75),
 ('Jamaica', 2008, 66),
 ('Jamaica', 2012, 62),
 ('Jamaica', 2016, 77),
 ('Jamaica', 2000, 65),
 ('Jamaica', 2004, 62),
 ('Jamaica', 1972, 51),

#### Problem 5
Display the names of all athletes who have won medals in more than one sport in the same year.

In [65]:
%%sql

SELECT DISTINCT ID,Year,Sport, COUNT(Medal) 
FROM olympics_data m1
    WHERE Medal IS NOT NULL
    GROUP BY ID, Sport, year
    HAVING COUNT(Medal)>1

 * mysql+pymysql://root:***@localhost:3306/olympics

[(1464, 2016, 'Swimming', 2),
 (7597, 2008, 'Fencing', 2),
 (11223, 1996, 'Gymnastics', 5),
 (17282, 1996, 'Swimming', 2),
 (17283, 1988, 'Athletics', 2),
 (17284, 2008, 'Swimming', 2),
 (17294, 2000, 'Shooting', 2),
 (17994, 2016, 'Archery', 2),
 (17996, 1992, 'Rowing', 2),
 (17996, 1996, 'Rowing', 2),
 (18003, 2016, 'Shooting', 2),
 (18005, 2016, 'Diving', 2),
 (20150, 2016, 'Diving', 2),
 (20180, 1988, 'Gymnastics', 6),
 (20187, 2004, 'Fencing', 2),
 (20194, 2016, 'Fencing', 2),
 (20203, 2000, 'Swimming', 2),
 (20203, 2004, 'Swimming', 2),
 (20205, 1988, 'Swimming', 2),
 (20212, 1988, 'Swimming', 2),
 (20212, 1992, 'Swimming', 2),
 (20216, 1984, 'Fencing', 2),
 (20217, 1988, 'Table Tennis', 2),
 (20228, 1936, 'Athletics', 3),
 (20232, 1996, 'Tennis', 2),
 (20237, 2008, 'Archery', 2),
 (20239, 1988, 'Table Tennis', 2),
 (20244, 1996, 'Shooting', 2),
 (20252, 1984, 'Swimming', 2),
 (20254, 2000, 'Badminton', 2),
 (20258, 2008, 'Diving', 2),
 (20258, 2012, 'Diving', 2),
 (20286, 1996, 'Athletics', 2),
 (20287, 1996, 'Shooting', 2),
 (20300, 2004, 'Swimming', 2),
 (20305, 1996, 'Swimming', 4),
 (20305, 2000, 'Swimming', 3),
 (20306, 1996, 'Swimming', 3),
 (20312, 2008, 'Gymnastics', 7),
 (20312, 2012, 'Gymnastics', 4),
 (20319, 1984, 'Gymnastics', 6),
 (20329, 1992, 'Athletics', 2),
 (20337, 1992, 'Table Tennis', 2),
 (20339, 2004, 'Swimming', 3),
 (20339, 2008, 'Swimming', 2),
 (20362, 2004, 'Gymnastics', 5),
 (20362, 2008, 'Gymnastics', 5),
 (20363, 2012, 'Swimming', 2),
 (20368, 2004, 'Swimming', 2),
 (20374, 2012, 'Archery', 2),
 (20618, 1936, 'Athletics', 2),
 (21360, 1984, 'Fencing', 2),
 (24240, 1984, 'Fencing', 3),
 (24911, 2012, 'Swimming', 2),
 (24913, 2012, 'Archery', 2),
 (27569, 2008, 'Gymnastics', 5),
 (27569, 2012, 'Gymnastics', 5),
 (27572, 2016, 'Gymnastics', 7),
 (27576, 1992, 'Table Tennis', 2),
 (27576, 1996, 'Table Tennis', 2),
 (28659, 1984, 'Swimming', 2),
 (28662, 2012, 'Table Tennis', 2),
 (28662, 2016, 'Table Tennis', 2),
 (29370, 2000, 'Gymnastics', 6),
 (29382, 1996, 'Fencing', 2),
 (29382, 2000, 'Fencing', 2),
 (29382, 2004, 'Fencing', 2),
 (30180, 2008, 'Shooting', 2),
 (30180, 2016, 'Shooting', 2),
 (30182, 1996, 'Athletics', 2),
 (30218, 1988, 'Athletics', 2),
 (30719, 1988, 'Archery', 2),
 (31163, 1992, 'Fencing', 2),
 (33945, 1996, 'Gymnastics', 8),
 (33946, 1988, 'Gymnastics', 6),
 (33947, 1996, 'Gymnastics', 5),
 (33951, 2004, 'Gymnastics', 5),
 (33952, 2016, 'Gymnastics', 4),
 (33974, 2012, 'Archery', 2),
 (34607, 1984, 'Swimming', 2),
 (34609, 1992, 'Rowing', 2),
 (34616, 1988, 'Swimming', 3),
 (34623, 2008, 'Cycling', 2),
 (34626, 2012, 'Gymnastics', 5),
 (37398, 1996, 'Diving', 2),
 (37398, 2000, 'Diving', 2),
 (37399, 1992, 'Archery', 2),
 (37399, 2000, 'Archery', 2),
 (37401, 2000, 'Swimming', 2),
 (37402, 2016, 'Swimming', 2),
 (38396, 1996, 'Canoeing', 2),
 (38399, 2000, 'Shooting', 2),
 (38399, 2004, 'Shooting', 2),
 (38404, 1992, 'Athletics', 2),
 (38414, 2000, 'Badminton', 2),
 (38414, 2004, 'Badminton', 2),
 (38417, 2008, 'Cycling', 2),
 (39255, 2000, 'Badminton', 2),
 (41418, 2016, 'Cycling', 3),
 (43411, 2004, 'Synchronized Swimming', 2),
 (43431, 1992, 'Rowing', 2),
 (43432, 2016, 'Archery', 2),
 (43453, 1992, 'Synchronized Swimming', 2),
 (43955, 1988, 'Canoeing', 2),
 (43956, 2008, 'Archery', 2),
 (43961, 1984, 'Swimming', 2),
 (43965, 2000, 'Diving', 2),
 (43965, 2004, 'Diving', 2),
 (43965, 2008, 'Diving', 2),
 (43970, 1988, 'Gymnastics', 8),
 (43971, 1992, 'Gymnastics', 8),
 (43977, 2012, 'Cycling', 3),
 (43980, 2012, 'Gymnastics', 7),
 (43986, 2008, 'Table Tennis', 2),
 (45493, 1996, 'Swimming', 2),
 (45493, 2000, 'Swimming', 4),
 (45498, 2004, 'Athletics', 2),
 (45880, 1992, 'Archery', 2),
 (45881, 2012, 'Swimming', 2),
 (46923, 1992, 'Swimming', 2),
 (46926, 2012, 'Swimming', 2),
 (46931, 2008, 'Gymnastics', 3),
 (46931, 2012, 'Gymnastics', 2),
 (46939, 1992, 'Gymnastics', 6),
 (46940, 1992, 'Rowing', 2),
 (46943, 1996, 'Archery', 2),
 (46943, 2000, 'Archery', 2),
 (46943, 2004, 'Archery', 2),
 (46948, 2012, 'Diving', 2),
 (49248, 1936, 'Athletics', 2),
 (50564, 2000, 'Diving', 2),
 (50566, 2008, 'Athletics', 2),
 (50580, 1988, 'Rowing', 2),
 (50586, 2000, 'Rowing', 2),
 (50609, 2008, 'Fencing', 2),
 (50614, 1996, 'Gymnastics', 8),
 (50626, 1996, 'Gymnastics', 7),
 (50630, 2000, 'Gymnastics', 4),
 (50637, 2012, 'Gymnastics', 5),
 (50639, 1984, 'Gymnastics', 6),
 (50642, 2004, 'Swimming', 3),
 (50655, 1988, 'Swimming', 3),
 (50656, 1992, 'Rowing', 2),
 (50659, 2000, 'Gymnastics', 6),
 (50659, 2004, 'Gymnastics', 6),
 (50659, 2008, 'Gymnastics', 5),
 (50660, 2012, 'Synchronized Swimming', 2),
 (50660, 2016, 'Synchronized Swimming', 2),
 (50662, 2004, 'Fencing', 2),
 (50667, 1936, 'Athletics', 2),
 (50674, 2008, 'Canoeing', 2),
 (50676, 2008, 'Equestrianism', 2),
 (51108, 2008, 'Diving', 2),
 (54746, 2012, 'Swimming', 2),
 (54747, 1996, 'Gymnastics', 5),
 (54764, 1988, 'Fencing', 2),
 (54764, 1992, 'Fencing', 2),
 (54770, 2004, 'Shooting', 2),
 (54770, 2008, 'Shooting', 2),
 (54773, 1996, 'Swimming', 3),
 (54784, 1988, 'Table Tennis', 2),
 (54788, 2008, 'Archery', 2),
 (54791, 1992, 'Shooting', 2),
 (54794, 2008, 'Synchronized Swimming', 2),
 (54796, 2008, 'Synchronized Swimming', 2),
 (54806, 2008, 'Gymnastics', 5),
 (54808, 2012, 'Swimming', 3),
 (54812, 1988, 'Table Tennis', 2),
 (54875, 1984, 'Swimming', 3),
 (54875, 1988, 'Swimming', 2),
 (54877, 2000, 'Swimming', 3),
 (58311, 1988, 'Canoeing', 2),
 (62431, 1996, 'Table Tennis', 2),
 (62431, 2000, 'Table Tennis', 2),
 (64739, 1996, 'Gymnastics', 5),
 (64739, 2000, 'Gymnastics', 5),
 (66592, 2000, 'Athletics', 2),
 (66593, 2004, 'Diving', 2),
 (66594, 1988, 'Fencing', 2),
 (67475, 1992, 'Swimming', 3),
 (67475, 1996, 'Swimming', 3),
 (68450, 2012, 'Fencing', 2),
 (68450, 2016, 'Fencing', 2),
 (69305, 1988, 'Athletics', 2),
 (69327, 1988, 'Gymnastics', 8),
 (69327, 1992, 'Gymnastics', 8),
 (69332, 1992, 'Gymnastics', 8),
 (69339, 1996, 'Shooting', 2),
 (69340, 1992, 'Tennis', 2),
 (69344, 1988, 'Athletics', 2),
 (69347, 1992, 'Gymnastics', 8),
 (69352, 2016, 'Swimming', 2),
 (69354, 2008, 'Fencing', 2),
 (69382, 1984, 'Fencing', 2),
 (69398, 1992, 'Rowing', 2),
 (69411, 1992, 'Gymnastics', 8),
 (69414, 1984, 'Swimming', 2),
 (69420, 2000, 'Table Tennis', 2),
 (69434, 1992, 'Gymnastics', 6),
 (69449, 2000, 'Synchronized Swimming', 2),
 (69454, 2000, 'Tennis', 2),
 (69454, 2012, 'Tennis', 2),
 (69455, 2000, 'Diving', 2),
 (69456, 2000, 'Fencing', 2),
 (69456, 2004, 'Fencing', 2),
 (69456, 2012, 'Fencing', 2),
 (69459, 1984, 'Gymnastics', 8),
 (69459, 1988, 'Gymnastics', 8),
 (69467, 2012, 'Canoeing', 2),
 (69476, 1988, 'Rowing', 2),
 (69483, 2008, 'Gymnastics', 4),
 (69496, 1988, 'Athletics', 2),
 (69499, 2004, 'Diving', 2),
 (69514, 1992, 'Cycling', 2),
 (69515, 2008, 'Archery', 2),
 (69518, 2016, 'Swimming', 3),
 (69526, 2000, 'Gymnastics', 7),
 (69526, 2004, 'Gymnastics', 5),
 (69526, 2008, 'Gymnastics', 6),
 (69527, 1984, 'Gymnastics', 8),
 (69529, 1992, 'Gymnastics', 8),
 (69529, 1996, 'Gymnastics', 8),
 (69530, 2012, 'Table Tennis', 2),
 (69530, 2016, 'Table Tennis', 2),
 (69532, 2012, 'Swimming', 2),
 (69536, 2008, 'Swimming', 2),
 (69536, 2012, 'Swimming', 2),
 (69538, 2000, 'Athletics', 2),
 (69543, 2004, 'Gymnastics', 5),
 (69560, 1992, 'Gymnastics', 6),
 (69569, 2000, 'Synchronized Swimming', 2),
 (69572, 1984, 'Gymnastics', 8),
 (69578, 2012, 'Swimming', 2),
 (69585, 2008, 'Equestrianism', 2),
 (69594, 2016, 'Swimming', 3),
 (69610, 2000, 'Rowing', 2),
 (69613, 1996, 'Fencing', 2),
 (69617, 1992, 'Archery', 2),
 (69618, 2000, 'Fencing', 2),
 (69619, 1988, 'Archery', 2),
 (69623, 1984, 'Swimming', 2),
 (69955, 2016, 'Gymnastics', 7),
 (69977, 1988, 'Swimming', 3),
 (69977, 1992, 'Swimming', 2),
 (69979, 2004, 'Gymnastics', 5),
 (69980, 1988, 'Swimming', 3),
 (69980, 1992, 'Swimming', 5),
 (69980, 1996, 'Swimming', 2),
 (69992, 2004, 'Archery', 2),
 (70303, 2000, 'Gymnastics', 5),
 (70551, 1932, 'Athletics', 2),
 (70551, 1936, 'Athletics', 3),
 (70572, 1996, 'Table Tennis', 2),
 (70572, 2000, 'Table Tennis', 2),
 (70573, 1984, 'Fencing', 2),
 (70579, 2004, 'Canoeing', 2),
 (70583, 1988, 'Cycling', 2),
 (70610, 1996, 'Swimming', 2),
 (70610, 2000, 'Swimming', 3),
 (70612, 2000, 'Rowing', 2),
 (70620, 2012, 'Synchronized Swimming', 2),
 (70634, 1988, 'Athletics', 2),
 (70647, 1996, 'Table Tennis', 2),
 (70650, 2004, 'Swimming', 2),
 (70659, 2012, 'Fencing', 2),
 (70662, 2000, 'Athletics', 2),
 (70668, 1992, 'Rowing', 2),
 (70669, 1996, 'Gymnastics', 6),
 (70669, 2000, 'Gymnastics', 6),
 (70677, 2016, 'Gymnastics', 3),
 (70681, 2000, 'Swimming', 2),
 (70700, 1984, 'Fencing', 3),
 (70700, 1988, 'Fencing', 2),
 (70703, 2012, 'Archery', 2),
 (71641, 1992, 'Swimming', 2),
 (71642, 1988, 'Swimming', 2),
 (71644, 1984, 'Gymnastics', 8),
 (71644, 1988, 'Gymnastics', 8),
 (71895, 1992, 'Swimming', 4),
 (71899, 1992, 'Swimming', 2),
 (71908, 1992, 'Rowing', 2),
 (71914, 1992, 'Gymnastics', 6),
 (71915, 1992, 'Table Tennis', 2),
 (71926, 2012, 'Swimming', 2),
 (71926, 2016, 'Swimming', 2),
 (71933, 2012, 'Swimming', 3),
 (71939, 1984, 'Fencing', 2),
 (71939, 1988, 'Fencing', 2),
 (72387, 1996, 'Archery', 2),
 (72392, 1948, 'Athletics', 3),
 (72394, 1988, 'Synchronized Swimming', 2),
 (72395, 2012, 'Fencing', 2),
 (72398, 2004, 'Swimming', 2),
 (72719, 1988, 'Canoeing', 2),
 (72724, 2012, 'Fencing', 2),
 (72724, 2016, 'Fencing', 2),
 (72731, 2004, 'Table Tennis', 2),
 (72731, 2008, 'Table Tennis', 2),
 (72735, 2016, 'Table Tennis', 2),
 (72739, 2016, 'Canoeing', 2),
 (72742, 1988, 'Archery', 2),
 (72744, 1992, 'Table Tennis', 2),
 (72747, 1988, 'Archery', 2),
 (72747, 1992, 'Archery', 2),
 (72751, 1984, 'Gymnastics', 6),
 (72755, 1988, 'Gymnastics', 6),
 (74677, 1996, 'Gymnastics', 6),
 (74678, 2016, 'Gymnastics', 2),
 (78706, 2004, 'Canoeing', 2),
 (78708, 2000, 'Fencing', 2),
 (78711, 2008, 'Cycling', 2),
 (80714, 1996, 'Gymnastics', 6),
 (82820, 1984, 'Swimming', 3),
 (85771, 1996, 'Swimming', 2),
 (86445, 1996, 'Shooting', 2),
 (86445, 2000, 'Shooting', 2),
 (86446, 1992, 'Canoeing', 2),
 (86449, 2016, 'Swimming', 4),
 (86569, 2004, 'Table Tennis', 2),
 (90147, 2000, 'Swimming', 3),
 (90950, 2008, 'Canoeing', 2),
 (91038, 2004, 'Swimming', 3),
 (91038, 2008, 'Swimming', 5),
 (91038, 2012, 'Swimming', 2),
 (91043, 2016, 'Shooting', 2),
 (93005, 2004, 'Diving', 2),
 (93011, 2008, 'Tennis', 2),
 (93011, 2012, 'Tennis', 2),
 (93011, 2016, 'Tennis', 2),
 (93012, 1996, 'Badminton', 2),
 (95672, 1936, 'Athletics', 3),
 (97367, 1996, 'Swimming', 2),
 (97752, 2000, 'Swimming', 3),
 (97752, 2004, 'Swimming', 4),
 (97752, 2008, 'Swimming', 2),
 (97755, 2016, 'Archery', 2),
 (97756, 1988, 'Swimming', 3),
 (97756, 1992, 'Swimming', 3),
 (97762, 1992, 'Table Tennis', 2),
 (97762, 1996, 'Table Tennis', 2),
 (97765, 1996, 'Gymnastics', 6),
 (97771, 2008, 'Diving', 2),
 (97771, 2012, 'Diving', 2),
 (97773, 2000, 'Athletics', 2),
 (97781, 2008, 'Shooting', 2),
 (97787, 2016, 'Swimming', 2),
 (99928, 2016, 'Canoeing', 2),
 (103153, 1988, 'Archery', 2),
 (105439, 2000, 'Diving', 2),
 (109210, 1996, 'Swimming', 6),
 (109218, 2016, 'Gymnastics', 5),
 (109246, 2012, 'Swimming', 2),
 (109533, 2016, 'Swimming', 5),
 (109535, 1996, 'Gymnastics', 8),
 (109536, 1984, 'Swimming', 3),
 (109536, 1988, 'Swimming', 5),
 (109536, 1992, 'Swimming', 2),
 (109537, 2008, 'Canoeing', 2),
 (109539, 1996, 'Archery', 2),
 (109551, 2004, 'Fencing', 2),
 (109676, 2016, 'Swimming', 3),
 (109683, 2016, 'Diving', 2),
 (111457, 1936, 'Athletics', 2),
 (116059, 2012, 'Athletics', 2),
 (116059, 2016, 'Athletics', 2),
 (116068, 2008, 'Fencing', 2),
 (116262, 2012, 'Gymnastics', 3),
 (116453, 2008, 'Fencing', 2),
 (116454, 2000, 'Swimming', 2),
 (116461, 2000, 'Rowing', 2),
 (116463, 1988, 'Fencing', 2),
 (116466, 2000, 'Table Tennis', 2),
 (116490, 1992, 'Rowing', 2),
 (116499, 2016, 'Synchronized Swimming', 2),
 (116505, 2008, 'Swimming', 3),
 (116505, 2012, 'Swimming', 4),
 (116505, 2016, 'Swimming', 3),
 (116508, 2008, 'Swimming', 2),
 (116508, 2012, 'Swimming', 2),
 (116510, 2004, 'Athletics', 2),
 (116511, 2016, 'Fencing', 2),
 (116514, 2012, 'Fencing', 2),
 (116514, 2016, 'Fencing', 2),
 (118268, 2016, 'Gymnastics', 2),
 (118276, 2008, 'Swimming', 2),
 (118277, 1988, 'Synchronized Swimming', 2),
 (118297, 2008, 'Fencing', 2),
 (118303, 2004, 'Shooting', 2),
 (118303, 2008, 'Shooting', 2),
 (118415, 1996, 'Archery', 2),
 (118415, 2000, 'Archery', 2),
 (118437, 1988, 'Cycling', 2),
 (118437, 1992, 'Cycling', 2),
 (118439, 2012, 'Swimming', 4),
 (118519, 2000, 'Shooting', 2),
 (118521, 1996, 'Badminton', 2),
 (119166, 2004, 'Gymnastics', 7),
 (120212, 2000, 'Diving', 2),
 (120212, 2004, 'Diving', 2),
 (120219, 1992, 'Athletics', 2),
 (121031, 1984, 'Gymnastics', 8),
 (128408, 1988, 'Swimming', 2),
 (128424, 1988, 'Gymnastics', 8),
 (128433, 2016, 'Archery', 2),
 (128452, 1992, 'Fencing', 2),
 (128452, 1996, 'Fencing', 2),
 (128452, 2000, 'Fencing', 2),
 (128452, 2004, 'Fencing', 2),
 (128456, 2004, 'Table Tennis', 2),
 (128456, 2008, 'Table Tennis', 2),
 (128456, 2012, 'Table Tennis', 2),
 (128459, 1984, 'Swimming', 3),
 (128462, 1992, 'Archery', 2),
 (128470, 1992, 'Fencing', 2),
 (128470, 1996, 'Fencing', 2),
 (128471, 1988, 'Gymnastics', 6),
 (128486, 2008, 'Athletics', 2),
 (128490, 2008, 'Fencing', 2),
 (128490, 2012, 'Fencing', 2),
 (128498, 1996, 'Athletics', 2),
 (128502, 2004, 'Canoeing', 2),
 (128503, 2004, 'Fencing', 2),
 (128503, 2008, 'Fencing', 2),
 (128509, 1992, 'Fencing', 2),
 (128513, 1992, 'Shooting', 2),
 (128520, 2008, 'Table Tennis', 2),
 (128524, 2000, 'Swimming', 2),
 (128539, 2000, 'Table Tennis', 2),
 (128539, 2004, 'Table Tennis', 2),
 (128539, 2008, 'Table Tennis', 2),
 (128549, 1984, 'Fencing', 2),
 (128558, 2012, 'Swimming', 3),
 (128565, 2016, 'Swimming', 2),
 (128566, 1992, 'Cycling', 2),
 (128569, 1992, 'Table Tennis', 2),
 (128569, 1996, 'Table Tennis', 2),
 (128572, 2004, 'Gymnastics', 6),
 (128584, 2000, 'Fencing', 2),
 (128587, 1988, 'Gymnastics', 6),
 (128593, 1988, 'Swimming', 2),
 (128593, 1992, 'Swimming', 2),
 (128594, 1992, 'Synchronized Swimming', 2),
 (128600, 1988, 'Gymnastics', 6),
 (128603, 1992, 'Archery', 2),
 (128603, 1996, 'Archery', 2),
 (128605, 2008, 'Diving', 2),
 (128610, 1988, 'Athletics', 2),
 (128617, 1996, 'Cycling', 2),
 (128617, 2000, 'Cycling', 2),
 (128618, 2016, 'Gymnastics', 6),
 (128626, 1988, 'Shooting', 2),
 (128626, 1992, 'Shooting', 2),
 (128626, 1996, 'Shooting', 2),
 (128626, 2000, 'Shooting', 2),
 (128652, 1988, 'Fencing', 2),
 (129297, 2016, 'Athletics', 2),
 (129596, 1988, 'Shooting', 2),
 (131787, 2004, 'Fencing', 2),
 (131791, 1984, 'Gymnastics', 6),
 (131792, 2016, 'Archery', 2),
 (131805, 2004, 'Diving', 2),
 (131805, 2008, 'Diving', 2),
 (131805, 2012, 'Diving', 2),
 (131809, 2004, 'Swimming', 4),
 (131809, 2012, 'Swimming', 2),
 (131832, 1984, 'Shooting', 2),
 (131838, 1996, 'Swimming', 3),
 (131844, 1996, 'Canoeing', 2),
 (131994, 1988, 'Swimming', 2),
 (132004, 1992, 'Fencing', 2),
 (132004, 1996, 'Fencing', 2),
 (132004, 2000, 'Fencing', 2),
 (132006, 2000, 'Diving', 2),
 (132009, 2000, 'Gymnastics', 6),
 (132011, 2004, 'Gymnastics', 7),
 (132011, 2008, 'Gymnastics', 6),
 (132014, 1992, 'Athletics', 2),
 (132018, 1988, 'Swimming', 3),
 (132018, 1992, 'Swimming', 3),
 (132024, 2000, 'Swimming', 4),
 (132025, 2004, 'Fencing', 2),
 (132027, 2016, 'Athletics', 2),
 (132028, 1988, 'Athletics', 2),
 (132038, 2000, 'Gymnastics', 7),
 (132038, 2004, 'Gymnastics', 7),
 (132039, 2004, 'Athletics', 2),
 (132041, 2012, 'Archery', 2),
 (132041, 2016, 'Archery', 2),
 (132045, 2000, 'Diving', 2),
 (132051, 2016, 'Fencing', 2),
 (132060, 1996, 'Canoeing', 2),
 (132061, 1988, 'Shooting', 2),
 (132061, 1992, 'Shooting', 2),
 (132065, 2016, 'Swimming', 3),
 (132068, 2012, 'Archery', 2),
 (132074, 2004, 'Canoeing', 2),
 (132079, 2008, 'Swimming', 2),
 (132081, 1992, 'Rowing', 2),
 (132085, 1984, 'Shooting', 3),
 (132085, 1988, 'Shooting', 3),
 (132096, 2004, 'Swimming', 4),
 (132096, 2008, 'Swimming', 2),
 (132105, 1988, 'Table Tennis', 2),
 (132109, 1984, 'Gymnastics', 8),
 (132109, 1988, 'Gymnastics', 8),
 (132110, 1988, 'Canoeing', 2),
 (132115, 2008, 'Archery', 2),
 (132407, 1984, 'Swimming', 3),
 (132408, 1996, 'Athletics', 2),
 (132413, 1988, 'Swimming', 3),
 (132413, 1992, 'Swimming', 3),
 (132422, 2008, 'Tennis', 2),
 (132467, 1992, 'Gymnastics', 6),
 (132468, 2000, 'Archery', 2),
 (132511, 1996, 'Archery', 2),
 (132511, 2000, 'Archery', 2),
 (132533, 2000, 'Fencing', 2),
 (132538, 1996, 'Athletics', 2),
 (132547, 2000, 'Gymnastics', 8),
 (132547, 2004, 'Gymnastics', 8),
 (132547, 2008, 'Gymnastics', 7),
 (132549, 2004, 'Canoeing', 2),
 (132551, 1988, 'Swimming', 3),
 (132551, 1992, 'Swimming', 2),
 (132554, 1988, 'Rowing', 2),
 (132568, 2008, 'Gymnastics', 5),
 (132573, 2000, 'Swimming', 3),
 (132573, 2004, 'Swimming', 3),
 (132574, 2000, 'Gymnastics', 6),
 (132576, 1992, 'Fencing', 2),
 (132625, 2012, 'Gymnastics', 5),
 (132630, 1988, 'Archery', 2),
 (132736, 1992, 'Fencing', 2),
 (132736, 1996, 'Fencing', 2),
 (132736, 2000, 'Fencing', 2),
 (132744, 2012, 'Swimming', 3),
 (132744, 2016, 'Swimming', 2),
 (132924, 1936, 'Swimming', 2),
 (132954, 1996, 'Tennis', 2),
 (132990, 2008, 'Fencing', 2),
 (132992, 2004, 'Canoeing', 2),
 (133174, 2016, 'Gymnastics', 5),
 (133313, 2016, 'Swimming', 3),
 (133317, 2000, 'Archery', 2),
 (133377, 2000, 'Athletics', 2),
 (133378, 2008, 'Tennis', 2),
 (133381, 2008, 'Badminton', 2),
 (133388, 1984, 'Fencing', 2),
 (133392, 1984, 'Athletics', 2),
 (133398, 2000, 'Fencing', 2),
 (133399, 2016, 'Athletics', 2),
 (133405, 1996, 'Swimming', 2),
 (134338, 1996, 'Swimming', 2),
 (134339, 2008, 'Tennis', 2),
 (134341, 2000, 'Athletics', 2),
 (134416, 2000, 'Swimming', 4),
 (134416, 2004, 'Swimming', 3),
 (134426, 2008, 'Equestrianism', 2),
 (134429, 1996, 'Shooting', 2),
 (134430, 1988, 'Athletics', 2),
 (134433, 2012, 'Gymnastics', 5),
 (134433, 2016, 'Gymnastics', 4),
 (134443, 2008, 'Swimming', 2),
 (134450, 1984, 'Athletics', 2),
 (134479, 2012, 'Table Tennis', 2),
 (134479, 2016, 'Table Tennis', 2),
 (134482, 1996, 'Gymnastics', 8),
 (134488, 2004, 'Archery', 2),
 (134488, 2008, 'Archery', 2),
 (134495, 2008, 'Cycling', 2),
 (134496, 2008, 'Fencing', 2),
 (134498, 2004, 'Fencing', 2),
 (134511, 2004, 'Swimming', 2),
 (134511, 2008, 'Swimming', 3),
 (134517, 2012, 'Cycling', 3),
 (134523, 2016, 'Badminton', 2),
 (134524, 2004, 'Gymnastics', 6),
 (134528, 2008, 'Athletics', 2),
 (134528, 2016, 'Athletics', 2),
 (134537, 1988, 'Shooting', 2),
 (134537, 1992, 'Shooting', 2),
 (134544, 2016, 'Tennis', 2),
 (134562, 1992, 'Gymnastics', 6),
 (134564, 1988, 'Rowing', 2),
 (134568, 2004, 'Synchronized Swimming', 2),
 (134573, 1988, 'Athletics', 2),
 (134583, 2016, 'Swimming', 2),
 (134585, 1996, 'Rowing', 2),
 (134603, 2008, 'Athletics', 2),
 (134604, 1988, 'Shooting', 2),
 (134604, 1992, 'Shooting', 2),
 (134605, 2004, 'Table Tennis', 2),
 (134605, 2008, 'Table Tennis', 2),
 (134617, 2016, 'Swimming', 3),
 (134624, 1988, 'Fencing', 2),
 (134634, 2000, 'Fencing', 2),
 (134636, 2000, 'Fencing', 2),
 (134636, 2004, 'Fencing', 2),
 (134646, 2008, 'Swimming', 3),
 (134646, 2012, 'Swimming', 2),
 (134652, 1996, 'Swimming', 2),
 (134667, 2004, 'Badminton', 2),
 (134672, 1992, 'Canoeing', 2),
 (134676, 1996, 'Swimming', 3),
 (134683, 2012, 'Badminton', 2),
 (134685, 2008, 'Equestrianism', 2),
 (134686, 1984, 'Fencing', 2),
 (134724, 1988, 'Athletics', 2),
 (134729, 1984, 'Swimming', 2),
 (134729, 1988, 'Swimming', 2),
 (134731, 2004, 'Tennis', 2),
 (134731, 2008, 'Tennis', 2),
 (134731, 2012, 'Tennis', 2),
 (134733, 2004, 'Swimming', 2),
 (134734, 2000, 'Gymnastics', 8),
 (134739, 2016, 'Tennis', 2),
 (134745, 1988, 'Fencing', 2),
 (134745, 1992, 'Fencing', 2),
 (134777, 2004, 'Canoeing', 2),
 (134777, 2008, 'Canoeing', 2),
 (134781, 2008, 'Fencing', 2),
 (134781, 2012, 'Fencing', 2),
 (134783, 2016, 'Cycling', 3),
 (134794, 2004, 'Fencing', 2),

#### Problem 6
What is the average weight difference between male and female athletes in the Olympics who have won a medal in the same event?

In [60]:
%%sql

SELECT AVG(t1.Weight - t2.Weight) 
FROM (SELECT * FROM olympics_data
    WHERE Medal IS NOT NULL) t1
    JOIN
    (SELECT * FROM olympics_data
    WHERE Medal IS NOT NULL) t2
    ON t1.Event = t2.Event AND
    t1.Sex != t2.Sex

 * mysql+pymysql://root:***@localhost:3306/olympics

[(Decimal('0.000000'),)]

#### Problem 7
How many patients have claimed more than the average claim amount for patients who are smokers and have at least one child, and belong to the southeast region?

In [ ]:
%%sql 

SELECT COUNT(*) FROM insurance_data
WHERE claim > (SELECT AVG(claim) FROM insurance.insurance_data
WHERE smoker='Yes' AND children>=1
AND region='southeast')
AND smoker='Yes' AND children=1
AND region='southeast'

#### Problem 8
How many patients have claimed more than the average claim amount for patients who are not smokers and have a BMI greater than the average BMI for patients who have at least one child?

#### Problem 9
How many patients have claimed more than the average claim amount for patients who have a BMI greater than the average BMI for patients who are diabetic, have at least one child, and are from the southwest region?

#### Problem 10:
What is the difference in the average claim amount between patients who are smokers and patients who are non-smokers, and have the same BMI and number of children?